### ISSUE TITLE
[Bug]: Enabling NCCL_SYMMETRIC as default fallback for AllReduce causes a segfault on B200/B300 when TP > 1

### ISSUE THREAD

**Issue by videodanchik** [NVIDIA/TensorRT-LLM#10255]
### System Info

I'm building `TensorRT-LLM` from source and here is a part of my building logs that includes the info about my `env`.

```
Saving detected profile to /root/.conan2/profiles/default
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Running command "nvcc -I src -Xcompiler -Wno-enum-compare --std=c++17 -o bin/print_traits.exe generated/print_kernel_traits.cu" to build "bin/print_traits.exe":
Running "bin/print_traits.exe":

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux


======== Computing dependency graph ========
conanfile.py (TensorRT-LLM/None): RUN: /root/py_env/.venv/bin/conan export /root/TensorRT-LLM/cpp/libnuma_conan.py --name=libnuma --version=system

======== Exporting recipe to the cache ========
libnuma/system: Exporting package recipe: /root/TensorRT-LLM/cpp/libnuma_conan.py
libnuma/system: exports: File 'conandata.yml' found. Exporting it...
libnuma/system: Copied 1 '.py' file: conanfile.py
libnuma/system: Copied 1 '.yml' file: conandata.yml
libnuma/system: Exported to cache folder: /root/.conan2/p/libnu646a5bc48499b/e
libnuma/system: Exported: libnuma/system#65d9e0e45ccc1e477b97d678fa7d56bb (2025-12-24 02:42:42 UTC)

Graph root
    conanfile.py (TensorRT-LLM/None): /root/TensorRT-LLM/cpp/conanfile.py
Requirements
    libnuma/system#65d9e0e45ccc1e477b97d678fa7d56bb - Cache

======== Computing necessary packages ========
Requirements
    libnuma/system#65d9e0e45ccc1e477b97d678fa7d56bb:63fead0844576fc02943e16909f08fcdddd6f44b#126c2f3a617d8971ef01085ba6a04bbd - Cache

======== Installing packages ========
libnuma/system: Already installed! (1 of 1)
libnuma/system: Using libnuma from: /usr/lib/x86_64-linux-gnu/libnuma.so

======== Finalizing install (deploy, generators) ========
conanfile.py (TensorRT-LLM/None): Calling generate()
conanfile.py (TensorRT-LLM/None): Generators folder: /root/TensorRT-LLM/cpp/build/conan
conanfile.py (TensorRT-LLM/None): CMakeDeps necessary find_package() and targets for your CMakeLists.txt
    find_package(libnuma)
    target_link_libraries(... libnuma::libnuma)
conanfile.py (TensorRT-LLM/None): CMakeToolchain generated: conan_toolchain.cmake
conanfile.py (TensorRT-LLM/None): CMakeToolchain: Preset 'conan-release' added to CMakePresets.json.
    (cmake>=3.23) cmake --preset conan-release
    (cmake<3.23) cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake  -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release
conanfile.py (TensorRT-LLM/None): CMakeToolchain generated: /root/TensorRT-LLM/cpp/build/conan/CMakePresets.json
conanfile.py (TensorRT-LLM/None): CMakeToolchain generated: /root/TensorRT-LLM/cpp/CMakeUserPresets.json
Install finished successfully
-- Using Conan toolchain: /root/TensorRT-LLM/cpp/build/conan/conan_toolchain.cmake
-- Conan toolchain: Defining architecture flag: -m64
-- Conan toolchain: C++ Standard 17 with extensions ON
-- The CXX compiler identification is GNU 13.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ENABLE_NVSHMEM is OFF
-- NVTX is disabled
-- Importing internal cutlass kernels
-- Building PyTorch
-- Building Google tests
-- Building benchmarks
-- Not building C++ micro benchmarks
-- TensorRT LLM version: 1.2.0rc7
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - /usr/local/cuda/bin/nvcc
-- CUDA compiler: /usr/local/cuda/bin/nvcc
-- The C compiler identification is GNU 13.3.0
-- The CUDA compiler identification is NVIDIA 13.0.88 with host compiler GNU 13.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Setting CMAKE_CUDA_ARCHITECTURES to all enables all architectures TensorRT LLM optimized for, not all architectures CUDA compiler supports.
-- GPU architectures: 80;86;89;90;100;120;103
-- Found CUDAToolkit: /usr/local/cuda/targets/x86_64-linux/include;/usr/local/cuda/targets/x86_64-linux/include/cccl (found suitable version "13.0.88", minimum required is "11.2")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- CUDA library status:
--     version: 13.0.88
--     libraries: /usr/local/cuda/targets/x86_64-linux/lib
--     include path: /usr/local/cuda/targets/x86_64-linux/include;/usr/local/cuda/targets/x86_64-linux/include/cccl
-- CUDA_NVML_LIB: CUDA::nvml
-- Found NCCL: /usr/lib/x86_64-linux-gnu/libnccl.so;/usr/lib/x86_64-linux-gnu/libnccl_static.a (found suitable version "2.28.9", minimum required is "2")
-- Found TensorRT: /usr/lib/x86_64-linux-gnu/libnvinfer.so (found suitable version "10.14.1.48", minimum required is "10") found components: OnnxParser
-- pybind11 v3.0.0 dev1
-- Found PythonInterp: /root/py_env/.venv/bin/python (found suitable version "3.12.12", minimum required is "3.8")
-- Found PythonLibs: /usr/local/lib/libpython3.12.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found Python: /root/py_env/.venv/bin/python3 (found suitable version "3.12.12", minimum required is "3.8") found components: Interpreter Development.Module Development.SABIModule
-- CUDAToolkit_VERSION 13.0 is greater or equal than 11.0, enable -DENABLE_BF16 flag
-- CUDAToolkit_VERSION 13.0 is greater or equal than 11.8, enable -DENABLE_FP8 flag
-- CUDAToolkit_VERSION 13.0 is greater or equal than 12.8, enable -DENABLE_FP4 flag
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1")
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
CMAKE_CUDA_FLAGS:  --expt-extended-lambda --expt-relaxed-constexpr --fatbin-options -compress-all
-- COMMON_HEADER_DIRS: /root/TensorRT-LLM/cpp
-- Found Python3: /root/py_env/.venv/bin/python3 (found version "3.12.12") found components: Interpreter Development Development.Module Development.Embed
/root/py_env/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
-- USE_CXX11_ABI is set by python Torch to 1
-- Set TORCH_CUDA_ARCH_LIST to placeholder value "8.0" to make Torch happy. This is NOT the list of architectures that will be compiled for.
-- Found Python executable at /root/py_env/.venv/bin/python3
-- Found Python libraries at /usr/local/lib
/root/py_env/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/root/py_env/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
-- Found CUDA: /usr/local/cuda (found version "13.0")
-- Found CUDAToolkit: /usr/local/cuda/include (found version "13.0.88")
-- PyTorch: CUDA detected: 13.0
-- PyTorch: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- PyTorch: CUDA toolkit directory: /usr/local/cuda
-- PyTorch: Header version is: 13.0
-- Found Python: /root/py_env/.venv/bin/python3 (found version "3.12.12") found components: Interpreter
CMake Warning at /root/py_env/.venv/lib/python3.12/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:140 (message):
  Failed to compute shorthash for libnvrtc.so
Call Stack (most recent call first):
  /root/py_env/.venv/lib/python3.12/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:86 (include)
  /root/py_env/.venv/lib/python3.12/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:509 (find_package)


-- USE_CUDNN is set to 0. Compiling without cuDNN support
-- USE_CUSPARSELT is set to 0. Compiling without cuSPARSELt support
-- USE_CUDSS is set to 0. Compiling without cuDSS support
-- USE_CUFILE is set to 0. Compiling without cuFile support
CMake Warning at /root/py_env/.venv/lib/python3.12/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:323 (message):
  pytorch is not compatible with `CMAKE_CUDA_ARCHITECTURES` and will ignore
  its value.  Please configure `TORCH_CUDA_ARCH_LIST` instead.
Call Stack (most recent call first):
  /root/py_env/.venv/lib/python3.12/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:86 (include)
  /root/py_env/.venv/lib/python3.12/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:509 (find_package)


-- Added CUDA NVCC flags for: -gencode;arch=compute_80,code=sm_80
CMake Warning at /root/py_env/.venv/lib/python3.12/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /root/py_env/.venv/lib/python3.12/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:125 (append_torchlib_if_found)
  CMakeLists.txt:509 (find_package)


-- Found Torch: /root/py_env/.venv/lib/python3.12/site-packages/torch/lib/libtorch.so
-- Removing Torch generated placeholder CUDA architecture flags: -gencode arch=compute_80,code=sm_80.
-- Found ucxx: /root/TensorRT-LLM/cpp/build/ucxx/build/ucxx-config.cmake (found version "0.42.0")
-- NIXL_ROOT not set, using default: /opt/nvidia/nvda_nixl
-- Could NOT find NIXL (missing: NIXL_INCLUDE_DIR NIXL_LIBRARY NIXL_BUILD_LIBRARY SERDES_LIBRARY) 
-- Could NOT find NIXL (missing: NIXL_INCLUDE_DIR NIXL_LIBRARY NIXL_BUILD_LIBRARY SERDES_LIBRARY) 
-- NIXL_LIBRARY: NIXL_LIBRARY-NOTFOUND
-- NIXL_BUILD_LIBRARY: NIXL_BUILD_LIBRARY-NOTFOUND
-- SERDES_LIBRARY: SERDES_LIBRARY-NOTFOUND
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- Operating System: ubuntu, 24.04
-- Using MPI_C_INCLUDE_DIRS: /usr/lib/x86_64-linux-gnu/openmpi/include;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi
-- Using MPI_C_LIBRARIES: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
running develop
/root/py_env/.venv/lib/python3.12/site-packages/setuptools/command/develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
WARNING: The user site-packages directory is disabled.
/root/py_env/.venv/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:90: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
Checking .pth file support in /root/.local/lib/python3.12/site-packages
/root/py_env/.venv/bin/python3 -E -c pass
TEST FAILED: /root/.local/lib/python3.12/site-packages does NOT support .pth files
bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /root/.local/lib/python3.12/site-packages

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.pypa.io/en/latest/deprecated/easy_install.html#custom-installation-locations


Please make the appropriate changes for your system and try again.
running egg_info
creating cutlass_library.egg-info
writing cutlass_library.egg-info/PKG-INFO
writing dependency_links to cutlass_library.egg-info/dependency_links.txt
writing top-level names to cutlass_library.egg-info/top_level.txt
writing manifest file 'cutlass_library.egg-info/SOURCES.txt'
reading manifest file 'cutlass_library.egg-info/SOURCES.txt'
adding license file 'LICENSE.txt'
writing manifest file 'cutlass_library.egg-info/SOURCES.txt'
running build_ext
Creating /root/.local/lib/python3.12/site-packages/cutlass-library.egg-link (link to .)

Installed /root/TensorRT-LLM/cpp/build/_deps/cutlass-src/python
Processing dependencies for cutlass-library==4.2.1
Finished processing dependencies for cutlass-library==4.2.1
-- Adding target _fpA_intB_gemm_src_instantiations_90 with instantiations for 90
-- Adding target _moe_gemm_src_instantiations_80 with instantiations for 80
-- Adding target _moe_gemm_src_instantiations_90 with instantiations for 90
-- Adding target _moe_gemm_src_instantiations_100 with instantiations for 100
-- Adding target _moe_gemm_src_instantiations_103 with instantiations for 103
-- Adding target _moe_gemm_src_instantiations_120 with instantiations for 120
-- Warning: Standard CMAKE_CXX_STANDARD value defined in conan_toolchain.cmake to 17 has been modified to 20 by /root/TensorRT-LLM/cpp/kernels/xqa/CMakeLists.txt
-- Found CUDAToolkit: /usr/local/cuda/targets/x86_64-linux/include;/usr/local/cuda/targets/x86_64-linux/include/cccl (found version "13.0.88")
-- Found Python3: /root/py_env/.venv/bin/python3 (found version "3.12.12") found components: Interpreter
-- UserBuffer ENABLE_MULTI_DEVICE is ON
-- libnuma found.
CMake Warning at /root/py_env/.venv/lib/python3.12/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /root/py_env/.venv/lib/python3.12/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:125 (append_torchlib_if_found)
  tensorrt_llm/executor/cache_transmission/ucx_utils/CMakeLists.txt:10 (find_package)


-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1")
-- Checking for module 'libzmq'
--   Found libzmq, version 4.3.5
-- USING_OSS_CUTLASS_LOW_LATENCY_GEMM
-- USING_OSS_CUTLASS_FP4_GEMM
-- USING_OSS_CUTLASS_MOE_GEMM
-- USING_OSS_CUTLASS_ALLREDUCE_GEMM
-- Enable open source Cutlass low latency gemm kernel
-- deep_ep DEEP_EP_CUDA_ARCHITECTURES: 90-real;100f-real;120a-real
-- flash_mla FLASH_MLA_ARCHS: 90;100;103
-- Building FlashMLA for architectures: 90;100;103
-- Configuring done (49.9s)
-- Generating done (7.0s)
-- Build files have been written to: /root/TensorRT-LLM/cpp/build
```

### Who can help?

Hi @nv-lschneider, I've noticed your [comment](https://github.com/NVIDIA/TensorRT-LLM/pull/8531#pullrequestreview-3608677008), and I think I'm running into a similar issue.

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

I'm encountering a segfault and I can reproduce it on B200/B300 GPUs when I run:
```
trtllm-serve serve --host 127.0.0.1 --port 8000 --max_batch_size 512 --max_num_tokens 131072 --pp_size 1 --tp_size 2 --ep_size 1 --kv_cache_free_gpu_memory_fraction 0.8 --extra_llm_api_options extra-llm-api-config.yml models--zai-org--GLM-4.5-Air/snapshots/a24ceef6ce4f3536971efe9b778bdaa1bab18daa
```

### Expected behavior

Everything should work.

### actual behavior

I can confirm that before [this PR](https://github.com/NVIDIA/TensorRT-LLM/pull/9314) everything worked for me correctly, but when I add your PR the following segfault occurs:
```
[TensorRT-LLM][INFO] Detecting local TP group for rank 0
[TensorRT-LLM][INFO] Detecting local TP group for rank 1
[TensorRT-LLM][INFO] TP group is intra-node for rank 0
[TensorRT-LLM][INFO] TP group is intra-node for rank 1
[TensorRT-LLM][INFO] Successfully loaded NCCL library: libnccl.so
[TensorRT-LLM][INFO] Successfully loaded NCCL library: libnccl.so
!!!!!!! Segfault encountered !!!!!!!
  File "./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c", line 0, in 0x000073d88a04532f
  File "<unknown>", line 0, in ncclCommWindowRegister
  File "<unknown>", line 0, in tensorrt_llm::_v1::common::nccl_util::NCCLWindowAllocator::allocateAndRegisterBuffer(ncclComm*, unsigned long, int)
  File "<unknown>", line 0, in tensorrt_llm::_v1::common::nccl_util::NCCLWindowAllocator::requestBuffer(ncclComm*, unsigned long)
  File "<unknown>", line 0, in tensorrt_llm::_v1::common::nccl_util::createNCCLWindowTensor(ncclComm*, c10::ArrayRef<long>, c10::ScalarType)
  File "<unknown>", line 0, in tensorrt_llm::_v1::torch_ext::(anonymous namespace)::AllreduceOp::run(at::Tensor const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, bool, std::optional<at::Tensor>)
  File "<unknown>", line 0, in tensorrt_llm::_v1::torch_ext::allreduce_raw(at::Tensor const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor>, c10::List<long> const&, long, long, double, bool)
  File "<unknown>", line 0, in c10::impl::make_boxed_from_unboxed_functor<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<std::vector<at::Tensor, std::allocator<at::Tensor> > (*)(at::Tensor const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor>, c10::List<long> const&, long, long, double, bool), std::vector<at::Tensor, std::allocator<at::Tensor> >, c10::guts::typelist::typelist<at::Tensor const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor>, c10::List<long> const&, long, long, double, bool> >, false>::call(c10::OperatorKernel*, c10::OperatorHandle const&, c10::DispatchKeySet, std::vector<c10::IValue, std::allocator<c10::IValue> >*)
  File "<unknown>", line 0, in c10::Dispatcher::callBoxed(c10::OperatorHandle const&, std::vector<c10::IValue, std::allocator<c10::IValue> >*) const [clone .isra.0]
  File "<unknown>", line 0, in torch::jit::invokeOperatorFromPython(c10::ArrayRef<std::shared_ptr<torch::jit::Operator> >, pybind11::args const&, pybind11::kwargs const&, std::optional<c10::DispatchKey>)
  File "<unknown>", line 0, in torch::jit::_get_operation_for_overload_or_packet(c10::ArrayRef<std::shared_ptr<torch::jit::Operator> >, c10::Symbol, pybind11::args const&, pybind11::kwargs const&, bool, std::optional<c10::DispatchKey>)
  File "<unknown>", line 0, in torch::jit::_get_operation_for_overload_or_packet(std::vector<std::shared_ptr<torch::jit::Operator>, std::allocator<std::shared_ptr<torch::jit::Operator> > > const&, c10::Symbol, pybind11::args const&, pybind11::kwargs const&, bool, std::optional<c10::DispatchKey>)
  File "<unknown>", line 0, in pybind11::cpp_function::initialize<torch::jit::initJITBindings(_object*)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#2}::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const::{lambda(pybind11::args const&, pybind11::kwargs const&)#1}, pybind11::object, pybind11::args const&, pybind11::kwargs const&, pybind11::name, pybind11::doc>(torch::jit::initJITBindings(_object*)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#2}::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const::{lambda(pybind11::args const&, pybind11::kwargs const&)#1}&&, pybind11::object (*)(pybind11::args const&, pybind11::kwargs const&), pybind11::name const&, pybind11::doc const&)::{lambda(pybind11::detail::function_call&)#1}::_FUN(pybind11::detail::function_call&)
  File "<unknown>", line 0, in pybind11::cpp_function::dispatcher(_object*, _object*, _object*)
  File "Objects/methodobject.c", line 537,!!!!!!! Segfault encountered !!!!!!!
  File "./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c", line 0, in 0x00007765f184532f
  File "<unknown>", line 0, in ncclCommWindowRegister
  File "<unknown>", line 0, in tensorrt_llm::_v1::common::nccl_util::NCCLWindowAllocator::allocateAndRegisterBuffer(ncclComm*, unsigned long, int)
  File "<unknown>", line 0, in tensorrt_llm::_v1::common::nccl_util::NCCLWindowAllocator::requestBuffer(ncclComm*, unsigned long)
  File "<unknown>", line 0, in tensorrt_llm::_v1::common::nccl_util::createNCCLWindowTensor(ncclComm*, c10::ArrayRef<long>, c10::ScalarType)
  File "<unknown>", line 0, in tensorrt_llm::_v1::torch_ext::(anonymous namespace)::AllreduceOp::run(at::Tensor const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, bool, std::optional<at::Tensor>)
  File "<unknown>", line 0, in tensorrt_llm::_v1::torch_ext::allreduce_raw(at::Tensor const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor>, c10::List<long> const&, long, long, double, bool)
  File "<unknown>", line 0, in c10::impl::make_boxed_from_unboxed_functor<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<std::vector<at::Tensor, std::allocator<at::Tensor> > (*)(at::Tensor const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor>, c10::List<long> const&, long, long, double, bool), std::vector<at::Tensor, std::allocator<at::Tensor> >, c10::guts::typelist::typelist<at::Tensor const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor> const&, std::optional<at::Tensor>, c10::List<long> const&, long, long, double, bool> >, false>::call(c10::OperatorKernel*, c10::OperatorHandle const&, c10::DispatchKeySet, std::vector<c10::IValue, std::allocator<c10::IValue> >*)
  File "<unknown>", line 0, in c10::Dispatcher::callBoxed(c10::OperatorHandle const&, std::vector<c10::IValue, std::allocator<c10::IValue> >*) const [clone .isra.0]
  File "<unknown>", line 0, in torch::jit::invokeOperatorFromPython(c10::ArrayRef<std::shared_ptr<torch::jit::Operator> >, pybind11::args const&, pybind11::kwargs const&, std::optional<c10::DispatchKey>)
  File "<unknown>", line 0, in torch::jit::_get_operation_for_overload_or_packet(c10::ArrayRef<std::shared_ptr<torch::jit::Operator> >, c10::Symbol, pybind11::args const&, pybind11::kwargs const&, bool, std::optional<c10::DispatchKey>)
  File "<unknown>", line 0, in torch::jit::_get_operation_for_overload_or_packet(std::vector<std::shared_ptr<torch::jit::Operator>, std::allocator<std::shared_ptr<torch::jit::Operator> > > const&, c10::Symbol, pybind11::args const&, pybind11::kwargs const&, bool, std::optional<c10::DispatchKey>)
  File "<unknown>", line 0, in pybind11::cpp_function::initialize<torch::jit::initJITBindings(_object*)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#2}::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const::{lambda(pybind11::args const&, pybind11::kwargs const&)#1}, pybind11::object, pybind11::args const&, pybind11::kwargs const&, pybind11::name, pybind11::doc>(torch::jit::initJITBindings(_object*)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#2}::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const::{lambda(pybind11::args const&, pybind11::kwargs const&)#1}&&, pybind11::object (*)(pybind11::args const&, pybind11::kwargs const&), pybind11::name const&, pybind11::doc const&)::{lambda(pybind11::detail::function_call&)#1}::_FUN(pybind11::detail::function_call&)
  File "<unknown>", line 0, in pybind11::cpp_function::dispatcher(_object*, _object*, _object*)
  File "Objects/methodobject.c", line 537, in cfunction_call
  File "Objects/call.c", line 367, in _PyObject_Call
  File "Objects/call.c", line 387, in PyCFunction_Call
  File "Python/bytecodes.c", line 3263, in _PyEval_EvalFrameDefault
  File "Objects/call.c", line 144, in _PyObject_FastCallDictTstate
  File "Objects/call.c", line 508, in _PyObject_Call_Prepend
...
```
and then a lot of similar logs of failures in Python. But the gist of the failure is probably in the `NCCL` memory allocation process as logs suggest, though I struggled to catch the exact issue with `gdb`. When I set `--tp_size 1`, the issue disappears. Hope this can help somehow with investigation.

### additional notes

I was working on adding `GLM-4.5-Air` to `TensorRT-LLM` (a few changes required compared to `GLM-4.6`) when I ran into this.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and checked the [documentation](https://nvidia.github.io/TensorRT-LLM/) and [examples](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples) for answers to frequently asked questions.

**Comment by nv-lschneider** [comment]
Thanks for reporting. I am taking a look

**Comment by nv-lschneider** [comment]
Hi @videodanchik can you share the `extra-llm-api-config.yml` file with me?
Also is the model open source available?

I am trying to repro and trying to find out if it is caused by that specific model or if I can repro it with another open source model.

Thank you that would help.

Also, there has been a small change to the code path, so if you could check if this still happens with TOT, that would be helpful too.

Thank you.

**Comment by videodanchik** [comment]
Hey @nv-lschneider, thanks for looking into this! After some careful dubugging I have realized that accidentally under the hood my `ucx` library ponters were linking to the system library available through `apt-get install libucx-dev ucx-utils`. I don't really know how it worked previously, but it worked :). When I compiled `ucx` from source using following commands:
```
git clone https://github.com/openucx/ucx.git
cd ucx
git checkout f656dbdf93e72e60b5d6ca78b9e3d9e744e789bd
./autogen.sh
./contrib/configure-release         \
    --prefix='/usr/local/ucx/'      \
    --enable-shared                 \
    --disable-static                \
    --disable-doxygen-doc           \
    --enable-optimizations          \
    --enable-cma                    \
    --enable-devel-headers          \
    --with-cuda='/usr/local/cuda'   \
    --with-verbs                    \
    --with-dm                       \
    --enable-mt
sudo make install -j$(nproc)
cd ..
sudo rm -rf ucx
echo 'export LD_LIBRARY_PATH=/usr/local/ucx/lib:${LD_LIBRARY_PATH}' >> ~/.bashrc
LD_LIBRARY_PATH=/usr/local/ucx/lib:${LD_LIBRARY_PATH}
```
After that the problem disappeared. I'm closing the issue, sorry for bothering you and thanks for help.
