### ISSUE TITLE
Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!

### ISSUE THREAD

**Issue by starlitsky2010** [NVIDIA/TensorRT-LLM#116]
Hi NVIDIA,

vocode launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "debug opencompass runner host",
            "type": "python",
            "request": "launch",
            "program": "run.py",
            "console": "integratedTerminal",
            "cwd": "${workspaceFolder}/tensorrt_llm/examples/llama",
            "justMyCode": false,
            "env": {
                "CUDA_VISIBLE_DEVICES": "1",
                "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:/usr/local/tensorrt/lib"
            },
            "args": [
                "--max_output_len",
                "50",
                "--tokenizer_dir",
                "/models/Llama-2-7b-chat-hf/",
                "--engine_dir",
                "/app/tensorrt_llm/examples/llama/tmp/llama/7B/trt_engines/fp16/1-gpu",
            ]
        },
    ]
}
```

When I used the launch.json above to run it by vscode it run failed with error logs below:

```
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    opal_init:startup:internal-failure
But I couldn't open the help file:
    /build-result/hpcx-v2.15-gcc-inbox-ubuntu22.04-cuda12-gdrcopy2-nccl2.17-x86_64/ompi/share/openmpi/help-opal-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    orte_init:startup:internal-failure
But I couldn't open the help file:
    /build-result/hpcx-v2.15-gcc-inbox-ubuntu22.04-cuda12-gdrcopy2-nccl2.17-x86_64/ompi/share/openmpi/help-orte-runtime: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    mpi_init:startup:internal-failure
But I couldn't open the help file:
    /build-result/hpcx-v2.15-gcc-inbox-ubuntu22.04-cuda12-gdrcopy2-nccl2.17-x86_64/ompi/share/openmpi/help-mpi-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[769c61956eee:05436] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

But when I used the following command to open the docker container to run the same command it run normally.

```
docker exec -it 769c61956eee /bin/bash
cd /app/tensorrt_llm/examples/llama
python3 run.py --max_output_len=200  --tokenizer_dir /models/Llama-2-7b-chat-hf/  --engine_dir=./tmp/llama/7B/trt_engines/fp16/1-gpu/
```
```
Logs:
Running the float16 engine ...
Input: "Born in north-east France, Soyer trained as a"
Output: " chef in Paris before moving to London in 1987. He has worked at several top restaurants, including the Michelin-starred Le Gavroche, and has been a food writer and broadcaster for over 20 years.

</s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s>"
```

I wonder how to debug this demo by vscode？

Thanks

**Comment by jdemouth-nvidia** [comment]
I’m afraid we won’t be able to help you on that one. We don’t have a lot of experience with VSCode. Let’s hope another user has run into that issue and has figured out a solution 🤞

**Comment by Luis-xu** [comment]
I met similar problems, and I solved it by adding MPI to the environment variables, referring to [https://github.com/open-mpi/ompi/issues/8058](https://github.com/open-mpi/ompi/issues/8058).
I hope this solution can help you.

**Comment by byshiue** [comment]
Close this bug because the issue is inactivated. Feel free to ask here if you still have question/issue, we will reopen the issue.

**Comment by lyc728** [comment]
> Hi NVIDIA,
> 
> vocode launch.json
> 
> ```
> {
>     // Use IntelliSense to learn about possible attributes.
>     // Hover to view descriptions of existing attributes.
>     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "debug opencompass runner host",
>             "type": "python",
>             "request": "launch",
>             "program": "run.py",
>             "console": "integratedTerminal",
>             "cwd": "${workspaceFolder}/tensorrt_llm/examples/llama",
>             "justMyCode": false,
>             "env": {
>                 "CUDA_VISIBLE_DEVICES": "1",
>                 "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:/usr/local/tensorrt/lib"
>             },
>             "args": [
>                 "--max_output_len",
>                 "50",
>                 "--tokenizer_dir",
>                 "/models/Llama-2-7b-chat-hf/",
>                 "--engine_dir",
>                 "/app/tensorrt_llm/examples/llama/tmp/llama/7B/trt_engines/fp16/1-gpu",
>             ]
>         },
>     ]
> }
> ```
> 
> When I used the launch.json above to run it by vscode it run failed with error logs below:
> 
> ```
> --------------------------------------------------------------------------
> Sorry!  You were supposed to get help about:
>     opal_init:startup:internal-failure
> But I couldn't open the help file:
>     /build-result/hpcx-v2.15-gcc-inbox-ubuntu22.04-cuda12-gdrcopy2-nccl2.17-x86_64/ompi/share/openmpi/help-opal-runtime.txt: No such file or directory.  Sorry!
> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> Sorry!  You were supposed to get help about:
>     orte_init:startup:internal-failure
> But I couldn't open the help file:
>     /build-result/hpcx-v2.15-gcc-inbox-ubuntu22.04-cuda12-gdrcopy2-nccl2.17-x86_64/ompi/share/openmpi/help-orte-runtime: No such file or directory.  Sorry!
> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> Sorry!  You were supposed to get help about:
>     mpi_init:startup:internal-failure
> But I couldn't open the help file:
>     /build-result/hpcx-v2.15-gcc-inbox-ubuntu22.04-cuda12-gdrcopy2-nccl2.17-x86_64/ompi/share/openmpi/help-mpi-runtime.txt: No such file or directory.  Sorry!
> --------------------------------------------------------------------------
> *** An error occurred in MPI_Init_thread
> *** on a NULL communicator
> *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
> ***    and potentially your MPI job)
> [769c61956eee:05436] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
> ```
> 
> But when I used the following command to open the docker container to run the same command it run normally.
> 
> ```
> docker exec -it 769c61956eee /bin/bash
> cd /app/tensorrt_llm/examples/llama
> python3 run.py --max_output_len=200  --tokenizer_dir /models/Llama-2-7b-chat-hf/  --engine_dir=./tmp/llama/7B/trt_engines/fp16/1-gpu/
> ```
> 
> ```
> Logs:
> Running the float16 engine ...
> Input: "Born in north-east France, Soyer trained as a"
> Output: " chef in Paris before moving to London in 1987. He has worked at several top restaurants, including the Michelin-starred Le Gavroche, and has been a food writer and broadcaster for over 20 years.
> 
> </s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s>"
> ```
> 
> I wonder how to debug this demo by vscode？
> 
> Thanks

Have you solved the problem
