### ISSUE TITLE
cuda out of memory when convert_checkpoint

### ISSUE THREAD

**Issue by wt2017** [NVIDIA/TensorRT-LLM#1221]
### System Info

CPU: x86_64
GPU: RTX 4080 16G
OS: fedora39
Deployment: 
- tensorrt_llm/devel:latest container based; deployed by kubernetes (with runtime crio).
- time-slice deployed by gpu-operator

MODEL: llama2-7b-hf : https://www.kaggle.com/datasets/lizhecheng/llama2-7b-hf?resource=download

ERROR Description: 
- cuda out of memory when do convert_checkpoint.py.
- pytorch allocates 15.05 GiB already
- sudo nvidia-smi as below
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      4741      G   /usr/libexec/Xorg                           115MiB |
|    0   N/A  N/A      5200      G   /usr/bin/gnome-shell                        112MiB |
|    0   N/A  N/A      5508      G   /usr/bin/gnome-software                      18MiB |
|    0   N/A  N/A      5787      G   /usr/libexec/xdg-desktop-portal-gnome        12MiB |
|    0   N/A  N/A      9709      G   ...seed-version=20240229-180128.736000       90MiB |
|    0   N/A  N/A     32620      C   python                                    **15652MiB** |
+---------------------------------------------------------------------------------------+

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

(1) deployment:
- container built based on Dockerfile as below

FROM localhost/tensorrt_llm_2/devel

RUN python3 -m pip install --upgrade pip
COPY tensorrt-llm.tar /workspace/tensorrt-llm.tar
RUN tar xvf tensorrt-llm.tar
WORKDIR /workspace/TensorRT-LLM/
RUN python3 ./scripts/build_wheel.py --clean  --trt_root /usr/local/tensorrt
RUN pip install ./build/tensorrt_llm*.whl

- kubernetes deploys pod with built container

(2) in container
- download model from https://www.kaggle.com/datasets/lizhecheng/llama2-7b-hf?resource=download
- copy into exmple/llama/7b
- execute : convert_checkpoint ( see error logs below )
- ERROR LOG:
root@fedora:/workspace/TensorRT-LLM/examples/llama# python convert_checkpoint.py --model_dir ./7b/                 --dtype float16                 --output_dir ./7b/trt_ckpt/fp16/1-gpu/
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev20240206000.9.0.dev2024020600
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.52s/it]
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:389: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:394: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
Traceback (most recent call last):
  File "/workspace/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 1547, in <module>
    main()
  File "/workspace/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 1523, in main
    covert_and_save(rank, convert_args)
  File "/workspace/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 1489, in covert_and_save
    weights = convert_hf_llama(
  File "/workspace/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 880, in convert_hf_llama
    qkv_weight = torch.cat([q_weight, k_weight, v_weight], dim=0)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB. GPU 0 has a total capacity of 15.69 GiB of which 104.38 MiB is free. Process 56670 has 15.29 GiB memory in use. Of the allocated memory 15.05 GiB is allocated by PyTorch, and 1.48 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Expected behavior

convert checkpoint successfully.

### actual behavior

OOM error is reported.

### additional notes
QUESTION: 
- how many GPU memory is required by convert_checkpoint for llama2-7b model ?
- any method to survive if GPU memory is less than required ?
- in theory, 7b model with float16 requires only 7*4/2 = 14GiB for inference ? why checkpoint convert requires more ?

**Comment by byshiue** [comment]
Could you try adding `--load_model_on_cpu`?

**Comment by wt2017** [comment]
> Could you try adding `--load_model_on_cpu`?

nothing changed.

root@fedora:/workspace/TensorRT-LLM/examples/llama# python convert_checkpoint.py --load-model-on-cpu --model_dir ./7b/ --dtype float16 --output_dir ./7b/trt_ckpt/fp16/1-gpu/
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev20240206000.9.0.dev2024020600
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:04<00:00,  2.46s/it]
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:389: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:394: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
Traceback (most recent call last):
  File "/workspace/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 1547, in <module>
    main()
  File "/workspace/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 1523, in main
    covert_and_save(rank, convert_args)
  File "/workspace/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 1489, in covert_and_save
    weights = convert_hf_llama(
  File "/workspace/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 880, in convert_hf_llama
    qkv_weight = torch.cat([q_weight, k_weight, v_weight], dim=0)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB. GPU 0 has a total capacity of 15.69 GiB of which 73.50 MiB is free. Process 103776 has 15.38 GiB memory in use. Of the allocated memory 15.15 GiB is allocated by PyTorch, and 1.48 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
root@fedora:/workspace/TensorRT-LLM/examples/llama#

**Comment by jeageun** [comment]
I also suffer the same problem. I just bypass this for now with debugger. 
In convert_checkpoint.py:1397 set the breakpoint.
After hit the breakpoint, jump to line 1404.
Then execute the following command.
`model = AutoModelForCausalLM.from_pretrained(args.model_dir,device_map='cpu',torch_dtype='auto' if not args.smoothquant else torch.float16,trust_remote_code=True)`

The problem that I saw was on `device_map`. If set it as auto, it uses gpu, and crash. With this, I bypass the OOM for the checkpoint conversion.

**Comment by nv-guomingz** [comment]
Hi@wt2017  we've resolved the most oom issue when converting checkpooint.
Could u please have a try with latest code base?
