### ISSUE TITLE
run after docker commit，“import tensorrt_llm” failed: “It looks like opal_init failed for some reason”

### ISSUE THREAD

**Issue by zhouxiao999** [NVIDIA/TensorRT-LLM#1294]
Environment

If applicable, please include the following:

CPU architecture : x86_64，192  AMD EPYC 7642 48-Core Processor
GPU name : A800

Libraries
TensorRT-LLM：0.9.0.dev2024031200
Versions of TensorRT, AMMO, CUDA, cuBLAS, etc. used：tensorrt                 9.3.0.post12.dev1；nvidia-ammo              0.7.4，nvidia-cublas-cu12       12.1.3.1
Container used：nvcr.io/nvidia/tritonserver:24.02-trtllm-python-py3
NVIDIA driver version：550.54.14
OS ：Ubuntu 22.04

Reproduction Steps

1. docker run -it --ipc=host --gpus all --privileged=true  --ulimit memlock=-1 --rm  -v  /home/zy/:/home/zy/ --shm-size="60g"   -p 8023:22 -p 7779:6666 --name="8023"  nvcr.io/nvidia/tritonserver:24.02-trtllm-python-py3    /bin/bash
2. apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev
3. pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com/
4. pip install mpmath==1.3.0
5. python3 -c "import tensorrt_llm"  success
6. docker commit xxx newimage，then docker run this newimage,python3 -c "import tensorrt_llm" fail!

```
root@ace5d7e1a45b:/home/zy/data8tb/zx/TensorRT-LLM/examples/bloom# python3 -c "import tensorrt_llm"
--------------------------------------------------------------------------
It looks like opal_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during opal_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_shmem_base_select failed
  --> Returned value -1 instead of OPAL_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_init failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Error" (-1) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[ace5d7e1a45b:00097] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!

```

**Comment by zhouxiao999** [comment]
update: After I changed the base image to nvidia/cuda:12.1.0-devel-ubuntu22.04, the problem was resolved.

**Comment by zhouxiao999** [comment]
After I changed the base image to nvidia/cuda:12.1.0-devel-ubuntu22.04, the problem was resolved.
