### ISSUE TITLE
Multi-node inference: invalid device ordinal

### ISSUE THREAD

**Issue by thies1006** [NVIDIA/TensorRT-LLM#1667]
### System Info

NCCL version 2.19.3+cuda12.0
TensorRT-LLM version: 0.11.0.dev2024052100
Ubuntu 22.04

### Who can help?

@byshiue

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I try to run Llama3-70B on two nodes which have 8 L4 GPUs each.
For this purpose I converted the model using TP=8, PP=2. I checked that the mapping in config.json is correct:
"world_size": 16
"tp_size": 8,
"pp_size": 2,
"gpus_per_node": 8

Now when I run the example script with mpirun like this: 
```mpirun -H $HOST1:8,$HOST2:8 -n 16 python3 examples/run.py ...```

### Expected behavior

script runs without errors

### actual behavior

I see errors like these:
```[TensorRT-LLM][ERROR] CUDA runtime error in cudaDeviceCanAccessPeer(&canAccessPeer, firstDeviceId, secondDeviceId): invalid device ordinal (/home/jenkins/agent/workspace/LLM/main/L0_PostMerge/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/allreducePlugin.cpp:341)```

### additional notes

I made sure that nccl-tests where running and there have been no problems.

**Comment by byshiue** [comment]
Please share the full end to end scripts to help reproducing your issue. But you can try disabling the `use_custom_all_reduce` (`--use_custom_all_reduce disable`) during building engine.

**Comment by thies1006** [comment]
Thank you. I'll try setting -use_custom_all_reduce disable.
In the meantime those where my exact scripts.
I wanted to note that by running on one single node (TP=8, PP=1) there are no problems.
```
#!/bin/bash
python /code/tensorrt_llm/examples/llama/convert_checkpoint.py --model_dir /code/tensorrt_llm/models/Meta-Llama-3-70B-Instruct/ \
                                --output_dir /code/tensorrt_llm/models/Meta-Llama-3-70B-Instruct-converted-16gpu/ \
                                --dtype float16 \
                                --vocab_size 128256 \
                                --inter_size 28672 \
                                --n_positions 8192 \
                                --n_layer 80 \
                                --n_head 64 \
                                --n_kv_head 8 \
                                --n_embd 8192 \
                                --rms_norm_eps 1e-05 \
                                --rotary_base 500000.0 \
                                --tp_size 8 \
                                --pp_size 2


trtllm-build --checkpoint_dir /code/tensorrt_llm/models/Meta-Llama-3-70B-Instruct-converted-16gpu/ \
                 --output_dir /code/tensorrt_llm/models/Meta-Llama-3-70B-Instruct-engine-16gpu/ \
                 --gemm_plugin float16 \
                 --workers 1 \
                 --tp_size 8 \
                 --pp_size 2 \
                 --gpt_attention_plugin float16 \
                 --context_fmha enable \
                 --remove_input_padding enable \
                 --use_custom_all_reduce enable \
                 --paged_kv_cache enable \
                 --use_paged_context_fmha enable \
                 --max_input_len 8192 \
                 --max_batch_size 1 \
                 --max_output_len 1024 \
                 --max_beam_width 1

mpirun -H $HOST1:8,$HOST2:8 -n 16 python3 examples/run.py \
   --engine_dir models/Meta-Llama-3-70B-Instruct-engine-16gpu/ \
   --max_output_len 64 \
   --tokenizer_dir models/Meta-Llama-3-70B-Instruct/ \
   --input_text "How do I count to nine in French?" \
   --run_profiling

```

**Comment by thies1006** [comment]
I get the same error when building the model with the said option -use_custom_all_reduce disable.

**Comment by byshiue** [comment]
Thanks for the try. It seems that the error happens at initializing the nccl plugin and not related to custom all reduce. 

This issue is fixed in latest main branch (commit id: f430a4b447ef4cba22698902d43eae0debf08594), please take a try.
