### ISSUE TITLE
Internlm2 only runs normally on adjacent GPUs.

### ISSUE THREAD

**Issue by yuanphoenix** [NVIDIA/TensorRT-LLM#1759]
### System Info

-GPU A800*8
Nvlink

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
python convert_checkpoint.py --model_dir /tensorrtllm_backend/triton_model_repo/tensorrt_llm/internlm2-chat-20b \
                --dtype bfloat16 \
                --output_dir ./internlm2-chat-20b/trt_engines/bf16/2-gpu/ \
                --tp_size 2
```

```

trtllm-build --checkpoint_dir  /app/tensorrt_llm/examples/internlm2/internlm2-chat-20b/trt_engines/bf16/2-gpu \
   --max_batch_size 8  --max_input_len 2048 \
   --max_output_len 2048  \
    --gemm_plugin bfloat16\
  --gpt_attention_plugin bfloat16 \
    --remove_input_padding enable  \
   --paged_kv_cache enable \
   --tp_size 2  \
   --use_custom_all_reduce enable \
    --output_dir /app/tensorrt_llm/examples/internlm2/engine_outputs
```

```
CUDA_VISIBLE_DEVICES=1,2  mpirun -n 2 --allow-run-as-root \
    python ../run.py --max_output_len=120 \
                     --input_text 'who are you？' \
                     --tokenizer_dir /tensorrtllm_backend/triton_model_repo/tensorrt_llm/internlm2-chat-20b \
                     --engine_dir /app/tensorrt_llm/examples/internlm2/engine_outputs \
                --use_py_session
```

### Expected behavior

it generate some sentence.

### actual behavior

```
[TensorRT-LLM] TensorRT-LLM version: 0.11.0.dev2024060400
[TensorRT-LLM] TensorRT-LLM version: 0.11.0.dev2024060400
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/internlm2/../run.py", line 632, in <module>
    main(args)
  File "/app/tensorrt_llm/examples/internlm2/../run.py", line 478, in main
    runner = runner_cls.from_dir(**runner_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/model_runner_cpp.py", line 222, in from_dir
    executor = trtllm.Executor(engine_dir, trtllm.ModelType.DECODER_ONLY,
RuntimeError: [TensorRT-LLM][ERROR] CUDA runtime error in ::cudaMallocAsync(ptr, n, mCudaStream->get()): out of memory (/app/tensorrt_llm/cpp/tensorrt_llm/runtime/tllmBuffers.h:117)
1       0x7f95c7df20a5 void tensorrt_llm::common::check<cudaError>(cudaError, char const*, char const*, int) + 149
2       0x7f95c9af2484 tensorrt_llm::runtime::BufferManager::gpu(unsigned long, nvinfer1::DataType) const + 324
3       0x7f95c9bbc724 tensorrt_llm::runtime::TllmRuntime::TllmRuntime(void const*, unsigned long, float, nvinfer1::ILogger&) + 644
4       0x7f95c9e0b822 tensorrt_llm::batch_manager::TrtGptModelInflightBatching::TrtGptModelInflightBatching(int, std::shared_ptr<nvinfer1::ILogger>, tensorrt_llm::runtime::ModelConfig const&, tensorrt_llm::runtime::WorldConfig const&, std::vector<unsigned char, std::allocator<unsigned char> > const&, bool, tensorrt_llm::executor::SchedulerConfig const&, tensorrt_llm::batch_manager::TrtGptModelOptionalParams const&) + 1506
5       0x7f95c9dc5400 tensorrt_llm::batch_manager::TrtGptModelFactory::create(std::vector<unsigned char, std::allocator<unsigned char> > const&, tensorrt_llm::runtime::ModelConfig const&, tensorrt_llm::runtime::WorldConfig const&, tensorrt_llm::batch_manager::TrtGptModelType, int, tensorrt_llm::executor::SchedulerConfig const&, tensorrt_llm::batch_manager::TrtGptModelOptionalParams const&) + 384
6       0x7f95c9e32f41 tensorrt_llm::executor::Executor::Impl::createModel(std::vector<unsigned char, std::allocator<unsigned char> > const&, tensorrt_llm::runtime::ModelConfig const&, tensorrt_llm::runtime::WorldConfig const&, tensorrt_llm::executor::ExecutorConfig const&) + 161
7       0x7f95c9e33538 tensorrt_llm::executor::Executor::Impl::loadModel(std::optional<std::filesystem::path> const&, std::optional<std::vector<unsigned char, std::allocator<unsigned char> > > const&, tensorrt_llm::runtime::GptJsonConfig const&, tensorrt_llm::executor::ExecutorConfig const&, bool) + 1256
8       0x7f95c9e33d8d tensorrt_llm::executor::Executor::Impl::Impl(std::filesystem::path const&, std::optional<std::filesystem::path> const&, tensorrt_llm::executor::ModelType, tensorrt_llm::executor::ExecutorConfig const&) + 1757
9       0x7f95c9e29210 tensorrt_llm::executor::Executor::Executor(std::filesystem::path const&, tensorrt_llm::executor::ModelType, tensorrt_llm::executor::ExecutorConfig const&) + 64
10      0x7f9647aece4d /usr/local/lib/python3.10/dist-packages/tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so(+0xafe4d) [0x7f9647aece4d]
11      0x7f9647a8f924 /usr/local/lib/python3.10/dist-packages/tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so(+0x52924) [0x7f9647a8f924]
12      0x55a44805a10e python(+0x15a10e) [0x55a44805a10e]
13      0x55a448050a7b _PyObject_MakeTpCall + 603
14      0x55a448068c20 python(+0x168c20) [0x55a448068c20]
15      0x55a448065087 python(+0x165087) [0x55a448065087]
16      0x55a448050e2b python(+0x150e2b) [0x55a448050e2b]
17      0x7f9647a8587d /usr/local/lib/python3.10/dist-packages/tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so(+0x4887d) [0x7f9647a8587d]
18      0x55a448050a7b _PyObject_MakeTpCall + 603
19      0x55a448049629 _PyEval_EvalFrameDefault + 27257
20      0x55a4480687f1 python(+0x1687f1) [0x55a4480687f1]
21      0x55a448069492 PyObject_Call + 290
22      0x55a4480455d7 _PyEval_EvalFrameDefault + 10791
23      0x55a44805a9fc _PyFunction_Vectorcall + 124
24      0x55a44804326d _PyEval_EvalFrameDefault + 1725
25      0x55a44803f9c6 python(+0x13f9c6) [0x55a44803f9c6]
26      0x55a448135256 PyEval_EvalCode + 134
27      0x55a448160108 python(+0x260108) [0x55a448160108]
28      0x55a4481599cb python(+0x2599cb) [0x55a4481599cb]
29      0x55a44815fe55 python(+0x25fe55) [0x55a44815fe55]
30      0x55a44815f338 _PyRun_SimpleFileObject + 424
31      0x55a44815ef83 _PyRun_AnyFileObject + 67
32      0x55a448151a5e Py_RunMain + 702
33      0x55a44812802d Py_BytesMain + 45
34      0x7f988c84bd90 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f988c84bd90]
35      0x7f988c84be40 __libc_start_main + 128
36      0x55a448127f25 _start + 37
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/internlm2/../run.py", line 632, in <module>
    main(args)
  File "/app/tensorrt_llm/examples/internlm2/../run.py", line 478, in main
    runner = runner_cls.from_dir(**runner_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/model_runner_cpp.py", line 222, in from_dir
    executor = trtllm.Executor(engine_dir, trtllm.ModelType.DECODER_ONLY,
RuntimeError: [TensorRT-LLM][ERROR] CUDA runtime error in ::cudaMallocAsync(ptr, n, mCudaStream->get()): out of memory (/app/tensorrt_llm/cpp/tensorrt_llm/runtime/tllmBuffers.h:117)
1       0x7f623f5f20a5 void tensorrt_llm::common::check<cudaError>(cudaError, char const*, char const*, int) + 149
2       0x7f62412f2484 tensorrt_llm::runtime::BufferManager::gpu(unsigned long, nvinfer1::DataType) const + 324
3       0x7f62413bc724 tensorrt_llm::runtime::TllmRuntime::TllmRuntime(void const*, unsigned long, float, nvinfer1::ILogger&) + 644
4       0x7f624160b822 tensorrt_llm::batch_manager::TrtGptModelInflightBatching::TrtGptModelInflightBatching(int, std::shared_ptr<nvinfer1::ILogger>, tensorrt_llm::runtime::ModelConfig const&, tensorrt_llm::runtime::WorldConfig const&, std::vector<unsigned char, std::allocator<unsigned char> > const&, bool, tensorrt_llm::executor::SchedulerConfig const&, tensorrt_llm::batch_manager::TrtGptModelOptionalParams const&) + 1506
5       0x7f62415c5400 tensorrt_llm::batch_manager::TrtGptModelFactory::create(std::vector<unsigned char, std::allocator<unsigned char> > const&, tensorrt_llm::runtime::ModelConfig const&, tensorrt_llm::runtime::WorldConfig const&, tensorrt_llm::batch_manager::TrtGptModelType, int, tensorrt_llm::executor::SchedulerConfig const&, tensorrt_llm::batch_manager::TrtGptModelOptionalParams const&) + 384
6       0x7f6241632f41 tensorrt_llm::executor::Executor::Impl::createModel(std::vector<unsigned char, std::allocator<unsigned char> > const&, tensorrt_llm::runtime::ModelConfig const&, tensorrt_llm::runtime::WorldConfig const&, tensorrt_llm::executor::ExecutorConfig const&) + 161
7       0x7f6241633538 tensorrt_llm::executor::Executor::Impl::loadModel(std::optional<std::filesystem::path> const&, std::optional<std::vector<unsigned char, std::allocator<unsigned char> > > const&, tensorrt_llm::runtime::GptJsonConfig const&, tensorrt_llm::executor::ExecutorConfig const&, bool) + 1256
8       0x7f6241633d8d tensorrt_llm::executor::Executor::Impl::Impl(std::filesystem::path const&, std::optional<std::filesystem::path> const&, tensorrt_llm::executor::ModelType, tensorrt_llm::executor::ExecutorConfig const&) + 1757
9       0x7f6241629210 tensorrt_llm::executor::Executor::Executor(std::filesystem::path const&, tensorrt_llm::executor::ModelType, tensorrt_llm::executor::ExecutorConfig const&) + 64
10      0x7f62bf2ece4d /usr/local/lib/python3.10/dist-packages/tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so(+0xafe4d) [0x7f62bf2ece4d]
11      0x7f62bf28f924 /usr/local/lib/python3.10/dist-packages/tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so(+0x52924) [0x7f62bf28f924]
12      0x561e453fd10e python(+0x15a10e) [0x561e453fd10e]
13      0x561e453f3a7b _PyObject_MakeTpCall + 603
14      0x561e4540bc20 python(+0x168c20) [0x561e4540bc20]
15      0x561e45408087 python(+0x165087) [0x561e45408087]
16      0x561e453f3e2b python(+0x150e2b) [0x561e453f3e2b]
17      0x7f62bf28587d /usr/local/lib/python3.10/dist-packages/tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so(+0x4887d) [0x7f62bf28587d]
18      0x561e453f3a7b _PyObject_MakeTpCall + 603
19      0x561e453ec629 _PyEval_EvalFrameDefault + 27257
20      0x561e4540b7f1 python(+0x1687f1) [0x561e4540b7f1]
21      0x561e4540c492 PyObject_Call + 290
22      0x561e453e85d7 _PyEval_EvalFrameDefault + 10791
23      0x561e453fd9fc _PyFunction_Vectorcall + 124
24      0x561e453e626d _PyEval_EvalFrameDefault + 1725
25      0x561e453e29c6 python(+0x13f9c6) [0x561e453e29c6]
26      0x561e454d8256 PyEval_EvalCode + 134
27      0x561e45503108 python(+0x260108) [0x561e45503108]
28      0x561e454fc9cb python(+0x2599cb) [0x561e454fc9cb]
29      0x561e45502e55 python(+0x25fe55) [0x561e45502e55]
30      0x561e45502338 _PyRun_SimpleFileObject + 424
31      0x561e45501f83 _PyRun_AnyFileObject + 67
32      0x561e454f4a5e Py_RunMain + 702
33      0x561e454cb02d Py_BytesMain + 45
34      0x7f6503fd9d90 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f6503fd9d90]
35      0x7f6503fd9e40 __libc_start_main + 128
36      0x561e454caf25 _start + 37
[server159:52902:0:52902] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x18)
[server159:52901:0:52901] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x18)
==== backtrace (tid:  52902) ====
 0 0x0000000000042520 __sigaction()  ???:0
 1 0x000000000002eb14 opal_hash_table_get_value_uint32()  /build-result/src/hpcx-v2.18-gcc-inbox-ubuntu22.04-cuda12-x86_64/ompi-efbeca7056b93dd17c67b66d1d514d39712e28d6/opal/class/opal_hash_table.c:334
 2 0x000000000002eb2c ompi_attr_delete_impl()  /build-result/src/hpcx-v2.18-gcc-inbox-ubuntu22.04-cuda12-x86_64/ompi-efbeca7056b93dd17c67b66d1d514d39712e28d6/ompi/attribute/attribute.c:1023
 3 0x0000000000030c64 ompi_attr_delete_all()  /build-result/src/hpcx-v2.18-gcc-inbox-ubuntu22.04-cuda12-x86_64/ompi-efbeca7056b93dd17c67b66d1d514d39712e28d6/ompi/attribute/attribute.c:1150
 4 0x0000000000033d3b ompi_comm_free()  /build-result/src/hpcx-v2.18-gcc-inbox-ubuntu22.04-cuda12-x86_64/ompi-efbeca7056b93dd17c67b66d1d514d39712e28d6/ompi/communicator/comm.c:1471
 5 0x000000000006b9ea PMPI_Comm_free()  /build-result/src/hpcx-v2.18-gcc-inbox-ubuntu22.04-cuda12-x86_64/ompi-efbeca7056b93dd17c67b66d1d514d39712e28d6/ompi/mpi/c/profile/pcomm_free.c:62
 6 0x0000000000881f09 tensorrt_llm::mpi::MpiComm::~MpiComm()  ???:0
 7 0x0000000000045495 secure_getenv()  ???:0
 8 0x0000000000045610 exit()  ???:0
 9 0x0000000000029d97 __libc_init_first()  ???:0
10 0x0000000000029e40 __libc_start_main()  ???:0
11 0x0000000000227f25 _start()  ???:0
=================================
[server159:52902] *** Process received signal ***
[server159:52902] Signal: Segmentation fault (11)
[server159:52902] Signal code:  (-6)
[server159:52902] Failing at address: 0xcea6
[server159:52902] [ 0] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f988c864520]
[server159:52902] [ 1] /opt/hpcx/ompi/lib/libopen-pal.so.40(opal_hash_table_get_value_uint32+0x4)[0x7f95c254eb14]
[server159:52902] [ 2] /opt/hpcx/ompi/lib/libmpi.so.40(+0x2eb2c)[0x7f95c6eacb2c]
[server159:52902] [ 3] /opt/hpcx/ompi/lib/libmpi.so.40(ompi_attr_delete_all+0x194)[0x7f95c6eaec64]
[server159:52902] [ 4] /opt/hpcx/ompi/lib/libmpi.so.40(ompi_comm_free+0x5b)[0x7f95c6eb1d3b]
[server159:52902] [ 5] /opt/hpcx/ompi/lib/libmpi.so.40(PMPI_Comm_free+0x1a)[0x7f95c6ee99ea]
[server159:52902] [ 6] /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so(_ZN12tensorrt_llm3mpi7MpiCommD1Ev+0x19)[0x7f95c7df5f09]
[server159:52902] [ 7] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x45495)[0x7f988c867495]
[server159:52902] [ 8] /usr/lib/x86_64-linux-gnu/libc.so.6(on_exit+0x0)[0x7f988c867610]
[server159:52902] [ 9] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x29d97)[0x7f988c84bd97]
[server159:52902] [10] /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7f988c84be40]
[server159:52902] [11] python(_start+0x25)[0x55a448127f25]
[server159:52902] *** End of error message ***
==== backtrace (tid:  52901) ====
 0 0x0000000000042520 __sigaction()  ???:0
 1 0x000000000002eb14 opal_hash_table_get_value_uint32()  /build-result/src/hpcx-v2.18-gcc-inbox-ubuntu22.04-cuda12-x86_64/ompi-efbeca7056b93dd17c67b66d1d514d39712e28d6/opal/class/opal_hash_table.c:334
 2 0x000000000002eb2c ompi_attr_delete_impl()  /build-result/src/hpcx-v2.18-gcc-inbox-ubuntu22.04-cuda12-x86_64/ompi-efbeca7056b93dd17c67b66d1d514d39712e28d6/ompi/attribute/attribute.c:1023
 3 0x0000000000030c64 ompi_attr_delete_all()  /build-result/src/hpcx-v2.18-gcc-inbox-ubuntu22.04-cuda12-x86_64/ompi-efbeca7056b93dd17c67b66d1d514d39712e28d6/ompi/attribute/attribute.c:1150
 4 0x0000000000033d3b ompi_comm_free()  /build-result/src/hpcx-v2.18-gcc-inbox-ubuntu22.04-cuda12-x86_64/ompi-efbeca7056b93dd17c67b66d1d514d39712e28d6/ompi/communicator/comm.c:1471
 5 0x000000000006b9ea PMPI_Comm_free()  /build-result/src/hpcx-v2.18-gcc-inbox-ubuntu22.04-cuda12-x86_64/ompi-efbeca7056b93dd17c67b66d1d514d39712e28d6/ompi/mpi/c/profile/pcomm_free.c:62
 6 0x0000000000881f09 tensorrt_llm::mpi::MpiComm::~MpiComm()  ???:0
 7 0x0000000000045495 secure_getenv()  ???:0
 8 0x0000000000045610 exit()  ???:0
 9 0x0000000000029d97 __libc_init_first()  ???:0
10 0x0000000000029e40 __libc_start_main()  ???:0
11 0x0000000000227f25 _start()  ???:0
=================================
[server159:52901] *** Process received signal ***
[server159:52901] Signal: Segmentation fault (11)
[server159:52901] Signal code:  (-6)
[server159:52901] Failing at address: 0xcea5
[server159:52901] [ 0] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f6503ff2520]
[server159:52901] [ 1] /opt/hpcx/ompi/lib/libopen-pal.so.40(opal_hash_table_get_value_uint32+0x4)[0x7f6239d4eb14]
[server159:52901] [ 2] /opt/hpcx/ompi/lib/libmpi.so.40(+0x2eb2c)[0x7f623e6acb2c]
[server159:52901] [ 3] /opt/hpcx/ompi/lib/libmpi.so.40(ompi_attr_delete_all+0x194)[0x7f623e6aec64]
[server159:52901] [ 4] /opt/hpcx/ompi/lib/libmpi.so.40(ompi_comm_free+0x5b)[0x7f623e6b1d3b]
[server159:52901] [ 5] /opt/hpcx/ompi/lib/libmpi.so.40(PMPI_Comm_free+0x1a)[0x7f623e6e99ea]
[server159:52901] [ 6] /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so(_ZN12tensorrt_llm3mpi7MpiCommD1Ev+0x19)[0x7f623f5f5f09]
[server159:52901] [ 7] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x45495)[0x7f6503ff5495]
[server159:52901] [ 8] /usr/lib/x86_64-linux-gnu/libc.so.6(on_exit+0x0)[0x7f6503ff5610]
[server159:52901] [ 9] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x29d97)[0x7f6503fd9d97]
[server159:52901] [10] /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7f6503fd9e40]
[server159:52901] [11] python(_start+0x25)[0x561e454caf25]
[server159:52901] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node server159 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

### additional notes

when CUDA_VISIBLE_DEVICES=0,1  or 2,3  it goes well.

**Comment by nv-guomingz** [comment]
Hi @yuanphoenix , thanks for reporting this issue, we'll try to reproduce it on our side firstly.

**Comment by nv-guomingz** [comment]
I tried to reproduce your issue with the latest release 0.11.0.dev2024061100 on H100x8 and it works.

Would u please check the gpu memory status before running the inference?

**Comment by nv-guomingz** [comment]
@yuanphoenix  I also suggest u have a try with the latest release  0.11.0.dev2024061100

**Comment by nv-guomingz** [comment]
Hi @yuanphoenix , Did u still meet the same issue with the latest code base?
If not, could we close this ticket?

**Comment by janpetrov** [comment]
the same issue even with v0.10.0

**Comment by janpetrov** [comment]
unfortunately, we are experiencing the same issue with llama2 70b models on 4xH100s and the newest tensorrt-llm version 0.11.0.dev2024062500, please see https://github.com/NVIDIA/TensorRT-LLM/issues/1868

**Comment by nv-guomingz** [comment]
@janpetrov  could u please share us the output of cmd `nvidia-smi topo -m`?

**Comment by janpetrov** [comment]
with pleasure, the output is [here](https://github.com/NVIDIA/TensorRT-LLM/issues/1868), with further data that you may find useful

**Comment by janpetrov** [comment]
please consider the comment there (and potentially an important discovery) that the bug depends on the driver version

**Comment by nv-guomingz** [comment]
> with pleasure, the output is [here](https://github.com/NVIDIA/TensorRT-LLM/issues/1868), with further data that you may find useful

Thanks, !1868 has a different gpu devices(4xh100) while this issue was found  A800*8, so my question is what's the network topo for those 8 gpus.

**Comment by janpetrov** [comment]
When I wrote above *unfortunately, we are experiencing the same issue with llama2 70b models **on 4xH100s** and the newest tensorrt-llm version 0.11.0.dev2024062500, please see ...* (emphasis on 4xH100s added), I just wanted to make you aware of the same / interrelated bug. I have not tested 8xH100s (it would take me some time before I could access 8 such gpus), but I quite presume that the result would be the same. I have no access to 8xA100s.

Nothing here that should prevent you from closing this issue #1759, if understood narrowly.

I just wanted to make you know that the issue here is most likely a manifestation of a complex bug related not only to a single model (internlm2) and not only to a single gpu configuration (8xA100).

**Comment by nv-guomingz** [comment]
Thanks for your explaination since I didn't find a  node which has the identical topo config in our internal cluster t you mentioned in #1868.

So it may take more time/effort to setup the env and rootcause the issue.

**Comment by janpetrov** [comment]
Thank you for the clarification. Please find the info that interests you as the last comment (freshly added) in [#1868](https://github.com/NVIDIA/TensorRT-LLM/issues/1868)

**Comment by janpetrov** [comment]
Please, is there any more feedback you are waiting for?

**Comment by janpetrov** [comment]
The bug has been fixed in version 0.12.

In version 0.11, if some GPUs are not mutually connected by an NVLink or SXM, you need to set use_custom_all_reduce to disable.

**Comment by yuanphoenix** [comment]
> 该 bug 已在 0.12 版本中修复。
> 
> 在 0.11 版本中，如果某些 GPU 没有通过 NVLink 或 SXM 相互连接，则需要将 use_custom_all_reduce 设置为 disable。

thank you
