### ISSUE TITLE
Nccl errors when running Llama 70b on 4 gpu

### ISSUE THREAD

**Issue by aditya2803** [NVIDIA/TensorRT-LLM#213]
Hi,

I tried running Llama 70b on 4 A100 Gpus (80GB, Single node), but ran into some nccl errors.

Command:  `mpirun -n 4 --allow-run-as-root python benchmark.py -m llama_70b --mode plugin --batch_size "1024" --input_output_len "512,200"`

Error: 

> Failed, NCCL error /src/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/allreducePlugin.cpp:295 'internal error - please report this issue to the NCCL developers'
> Failed, NCCL error /src/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/allreducePlugin.cpp:295 'internal error - please report this issue to the NCCL developers'
> Failed, NCCL error /src/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/allreducePlugin.cpp:295 'internal error - please report this issue to the NCCL developers'
> Failed, NCCL error /src/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/allreducePlugin.cpp:295 'internal error - please report this issue to the NCCL developers'
> --------------------------------------------------------------------------
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.
> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> mpirun detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
> 
>   Process name: [[59172,1],2]
>   Exit code:    1
> --------------------------------------------------------------------------

I get this same error when building the tensorrt engine and then running the run.py file.

**Comment by jdemouth-nvidia** [comment]
Hi @aditya2803 ,

Can you share the command you use to build the engine, please?

Also, on your system do you have 4 GPUs or more? And how are they connected?

Finally, can you verify that a simple NCCL test works as expected, please?

Thanks,
Julien

**Comment by aditya2803** [comment]
Hi,

Closing this issue as it was related to the topology of GPUs in my node.

**Comment by isky-cd** [comment]
> Hi,
> 
> Closing this issue as it was related to the topology of GPUs in my node.

Hi, I encountered the same problem. Could you please tell me how did you solve it?

**Comment by ethnzhng** [comment]
@yuehuayingxueluo Hi, not sure if you solved it already, but in my case, I fixed the issue by including the flags `--ipc=host --ulimit memlock=-1 --ulimit stack=67108864 --gpus=all` when running the container - I think it had to do with the stack limit.

https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md#on-systems-without-gnu-make

**Comment by isky-cd** [comment]
> @yuehuayingxueluo Hi, not sure if you solved it already, but in my case, I fixed the issue by including the flags `--ipc=host --ulimit memlock=-1 --ulimit stack=67108864 --gpus=all` when running the container - I think it had to do with the stack limit.
> 
> https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md#on-systems-without-gnu-make

Thank you for your help. I have resolved this problem, by remove '--net host' when running the container. But I haven't encountered such a problem on other machines.
