### ISSUE TITLE
Error: convert_checkpoint in TensorRT-LLM for Llama3.2 3B when tested on multiple versions

### ISSUE THREAD

**Issue by DeekshithaDPrakash** [NVIDIA/TensorRT-LLM#2471]
### System Info

GPU: A100
Ubuntu: Ubuntu 22.04.4 LTS

Command:

```
CONVERT_CHKPT_SCRIPT=/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py
python3 ${CONVERT_CHKPT_SCRIPT} --model_dir ${LLAMA_MODEL} --output_dir ${UNIFIED_CKPT_PATH} --dtype float16
```

- tritonserver:24.09-trtllm-python-py3
- TensorRT-LLM: 0.13
- tenorrrtllm_backend: 0.13
- transformers: 
   Actual version: 4.42.4 gives the following error,

```
[TensorRT-LLM] TensorRT-LLM version: 0.13.0
0.13.0
[11/20/2024-08:06:21] [TRT-LLM] [W] AutoConfig cannot load the huggingface config.
Traceback (most recent call last):
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 503, in <module>
    main()
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 495, in main
    convert_and_save_hf(args)
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 437, in convert_and_save_hf
    execute(args.workers, [convert_and_save_rank] * world_size, args)
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 444, in execute
    f(args, rank)
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 423, in convert_and_save_rank
    llama = LLaMAForCausalLM.from_hugging_face(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 320, in from_hugging_face
    config = LLaMAConfig.from_hugging_face(hf_config_or_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/config.py", line 101, in from_hugging_face
    hf_config = transformers.AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 989, in from_pretrained
    return config_class.from_dict(config_dict, **unused_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 772, in from_dict
    config = cls(**config_dict)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/configuration_llama.py", line 161, in __init__
    self._rope_scaling_validation()
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/configuration_llama.py", line 182, in _rope_scaling_validation
    raise ValueError(
ValueError: `rope_scaling` must be a dictionary with two fields, `type` and `factor`, got {'factor': 32.0, 'high_freq_factor': 4.0, 'low_freq_factor': 1.0, 'original_max_position_embeddings': 8192, 'rope_type': 'llama3'}

```
  Upgarded verion: 4.45.2 gives the following error,
```
[TensorRT-LLM] TensorRT-LLM version: 0.13.0
0.13.0
201it [00:00, 260.82it/s]
Traceback (most recent call last):
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 503, in <module>
    main()
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 495, in main
    convert_and_save_hf(args)
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 437, in convert_and_save_hf
    execute(args.workers, [convert_and_save_rank] * world_size, args)
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 444, in execute
    f(args, rank)
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 423, in convert_and_save_rank
    llama = LLaMAForCausalLM.from_hugging_face(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 358, in from_hugging_face
    loader.generate_tllm_weights(model)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/model_weights_loader.py", line 357, in generate_tllm_weights
    self.load(tllm_key,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/model_weights_loader.py", line 278, in load
    v = sub_module.postprocess(tllm_key, v, **postprocess_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/layers/linear.py", line 391, in postprocess
    weights = weights.to(str_dtype_to_torch(self.dtype))
AttributeError: 'NoneType' object has no attribute 'to'
Exception ignored in: <function PretrainedModel.__del__ at 0x7fec26679870>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 453, in __del__
    self.release()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 450, in release
    release_gc()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_utils.py", line 471, in release_gc
    torch.cuda.ipc_collect()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 901, in ipc_collect
    _lazy_init()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 330, in _lazy_init
    raise DeferredCudaCallError(msg) from e
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: 'NoneType' object is not iterable

CUDA call was originally invoked at:

  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 8, in <module>
    from transformers import AutoConfig
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/__init__.py", line 27, in <module>
    from .chat_template_utils import DocstringParsingException, TypeHintParsingException, get_json_schema
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/chat_template_utils.py", line 39, in <module>
    from torch import Tensor
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1689, in <module>
    _C._initExtension(manager_path())
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 1467, in <module>
    _lazy_call(_register_triton_kernels)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 253, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))

```
   

The same error comes with other TensorRT-LLM versions like 0.14 for tritonserver:24.08-trtllm-python-py3, tritonserver:24.09-trtllm-python-py3, as well as tritonserver:24.10-trtllm-python-py3

I'm now assuming that this is a bug! as there are multiple users facing the same issue : #2467 #2339 #2320 

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. sudo docker run -it --net host --shm-size=4g --name triton_llm_llama32 --ulimit memlock=-1 --ulimit stack=67108864 --gpus '"device=1"' -v /local_mnt_folder/:/opt/tritonserver/TensorRT_LLM nvcr.io/nvidia/tritonserver:24.09-trtllm-python-py3
2. apt-get update
apt-get install -y openmpi-bin openmpi-common libopenmpi-dev git git-lfs
3. cd TensorRT_LLM
4. git clone -b v0.13.0 https://github.com/triton-inference-server/tensorrtllm_backend.git
git clone --branch v0.13.0 https://github.com/NVIDIA/TensorRT-LLM.git
5. CONVERT_CHKPT_SCRIPT=/opt/tritonserver/TensorRT_LLM/TensorRT-LLM/examples/llama/convert_checkpoint.py
LLAMA_MODEL=/opt/tritonserver/TensorRT_LLM/llama3_2_model
UNIFIED_CKPT_PATH=/opt/tritonserver/TensorRT_LLM/ckpt/llaam32/3b
ENGINE_DIR=/opt/tritonserver/TensorRT_LLM/engines/1-gpu
6. python3 ${CONVERT_CHKPT_SCRIPT} --model_dir ${LLAMA_MODEL} --output_dir ${UNIFIED_CKPT_PATH} --dtype float16

### Expected behavior

The convert_checkpoint runs smoothly and creates two files inside the checkpoint folder:
1. config.json
2. rank0.safetensors

### actual behavior

Lower transformer version gives `rope_scaling` error, while a higher version(>=4.45.1) as described by llama3.2 gives CUDA error: torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: 'NoneType' object is not iterable

### additional notes

I think there's surely version mismatch

**Comment by jayakommuru** [comment]
+1
Facing the same issue

**Comment by jayakommuru** [comment]
HI @byshiue can you help with this?

**Comment by byshiue** [comment]
For stable branch, llama 3.2 is supported since release 0.15. 

If you want to run test now, you need to use main branch to deploy.

**Comment by DeekshithaDPrakash** [comment]
> For stable branch, llama 3.2 is supported since release 0.15.
> 
> If you want to run test now, you need to use main branch to deploy.

@byshiue Thank you for your response. I truly appreciate your guidance.

I will test the following and update here soon.

1. https://github.com/triton-inference-server/tensorrtllm_backend.git 
2. tritonserver:24.10-trtllm-python-py3 
3. https://github.com/NVIDIA/TensorRT-LLM.git

**Comment by DeekshithaDPrakash** [comment]
I tested with stable branches of both TensorRT-LLM as well as tensorrtllm-backend with varied tensorrt-llm repos:

The error still remains when convert_checkpoint.py is executed.

Command: 
```python
python3 ${CONVERT_CHKPT_SCRIPT} --model_dir ${LLAMA_MODEL} --output_dir ${UNIFIED_CKPT_PATH} --dtype float16
``` 

Upgraded tensorrt-llm versions within the docker container using: pip install -U tensorrt-llm==version_no

1. tensort-llm version 0.14.0

Error:

```
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
[TensorRT-LLM] TensorRT-LLM version: 0.14.0
Traceback (most recent call last):
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 16, in <module>
    from tensorrt_llm.models.convert_utils import infer_dtype
ImportError: cannot import name 'infer_dtype' from 'tensorrt_llm.models.convert_utils' (/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/convert_utils.py)
```

2. tensort-llm version 0.15.0.dev2024101500

Error:

```
Traceback (most recent call last):
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 10, in <module>
    import tensorrt_llm
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/__init__.py", line 32, in <module>
    import tensorrt_llm.functional as functional
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/functional.py", line 28, in <module>
    from . import graph_rewriting as gw
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/graph_rewriting.py", line 12, in <module>
    from .network import Network
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/network.py", line 27, in <module>
    from tensorrt_llm.module import Module
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/module.py", line 17, in <module>
    from ._common import default_net
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_common.py", line 37, in <module>
    from ._utils import str_dtype_to_trt
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_utils.py", line 31, in <module>
    from tensorrt_llm.bindings import GptJsonConfig
ImportError: /usr/local/lib/python3.10/dist-packages/tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKSs
```


3. tensorrt-llm version 0.15.0.dev2024102900

Error:

```
[TensorRT-LLM] TensorRT-LLM version: 0.15.0.dev2024102900
Traceback (most recent call last):
  File "/opt/tritonserver/TensorRT_LLM/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 16, in <module>
    from tensorrt_llm.models.convert_utils import infer_dtype
ImportError: cannot import name 'infer_dtype' from 'tensorrt_llm.models.convert_utils' (/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/convert_utils.py)
```

The clear solution is not yet found!!!

**Comment by mihkeltiks** [comment]
I fixed this by doing `pip install -r requirements.txt` in  `/opt/tritonserver/TensorRT_LLM/TensorRT-LLM/examples/llama`. I had to add an --extra-index-url for tensorrt_llm though. I didn't get the `infer_dtype` error afterwards.

**Comment by DeekshithaDPrakash** [comment]
> I fixed this by doing `pip install -r requirements.txt` in `/opt/tritonserver/TensorRT_LLM/TensorRT-LLM/examples/llama`. I had to add an --extra-index-url for tensorrt_llm though. I didn't get the `infer_dtype` error afterwards.

Thank you for your response :)

Could you please tell me your TensorRT-LLM, tensorrtllm-backend as well as Docker container image versions?

Also, it would be very helpful if you could list down installed libraries here using "pip list" within your docker container.

I am still facing the infer_dtype issue with 0.14.0 TensorRT-LLM version even after using--extra-index-url  and if I use the latest version (0.16.0) there is tensorrt version compatibility issue


```
0.14.0
201it [00:07, 25.98it/s]
Traceback (most recent call last):
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 518, in <module>
    main()
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 510, in main
    convert_and_save_hf(args)
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 452, in convert_and_save_hf
    execute(args.workers, [convert_and_save_rank] * world_size, args)
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 459, in execute
    f(args, rank)
  File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 438, in convert_and_save_rank
    llama = LLaMAForCausalLM.from_hugging_face(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 360, in from_hugging_face
    loader.generate_tllm_weights(model)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/model_weights_loader.py", line 408, in generate_tllm_weights
    self.load(tllm_key,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/model_weights_loader.py", line 296, in load
    v = sub_module.postprocess(tllm_key, v, **postprocess_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/layers/linear.py", line 407, in postprocess
    weights = weights.to(str_dtype_to_torch(self.dtype))
AttributeError: 'NoneType' object has no attribute 'to'

```

**Comment by mihkeltiks** [comment]
So I use `nvcr.io/nvidia/tritonserver:24.10-trtllm-python-py3`. If I follow the steps for inference server (in https://github.com/triton-inference-server/tutorials/blob/main/Popular_Models_Guide/Llama2/trtllm_guide.md)  from `HF_LLAMA_MODEL= ...` until the checkpoint I get this. 
```
[TensorRT-LLM] TensorRT-LLM version: 0.14.0
Traceback (most recent call last):
  File "/tensorrtllm_backend/tensorrt_llm/examples/llama/convert_checkpoint.py", line 16, in <module>
    from tensorrt_llm.models.convert_utils import infer_dtype
ImportError: cannot import name 'infer_dtype' from 'tensorrt_llm.models.convert_utils' (/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/convert_utils.py)
```
If I do in the folder I added this to the first line in requirements.txt `--extra-index-url https://pypi.nvidia.com/ tensorrt-llm` and afterwards `pip install -r requirements.txt`, the error is gone. I also had to uninstall and reinstall tensorrt for some reason. `pip list` gives the following before and after:

Before
```
tensorrt           10.4.0
tensorrt-llm       0.14.0
tokenizers         0.20.1
tomli              2.0.2
torch              2.4.0a0+3bcc3cddb5.nv24.7
torchprofile       0.0.4
torchvision        0.19.0a0
tqdm               4.66.6
transformers       4.45.1
```

After
```
tensorrt                 10.6.0.post1
tensorrt-cu12            10.6.0.post1
tensorrt-cu12-bindings   10.6.0.post1
tensorrt-cu12-libs       10.6.0.post1
tensorrt_llm             0.16.0.dev2024111900
tokenizers               0.20.1
tomli                    2.0.2
torch                    2.5.1
torchprofile             0.0.4
torchvision              0.20.1
tqdm                     4.66.6
transformers             4.45.1
triton                   3.1.0

```

The code for the Llamas repo I am using this, which could be the difference here also: https://huggingface.co/tartuNLP/Llammas-base-AEG

**Comment by DeekshithaDPrakash** [comment]
> So I use `nvcr.io/nvidia/tritonserver:24.10-trtllm-python-py3`. If I follow the steps for inference server (in https://github.com/triton-inference-server/tutorials/blob/main/Popular_Models_Guide/Llama2/trtllm_guide.md) from `HF_LLAMA_MODEL= ...` until the checkpoint I get this.
> 
> ```
> [TensorRT-LLM] TensorRT-LLM version: 0.14.0
> Traceback (most recent call last):
>   File "/tensorrtllm_backend/tensorrt_llm/examples/llama/convert_checkpoint.py", line 16, in <module>
>     from tensorrt_llm.models.convert_utils import infer_dtype
> ImportError: cannot import name 'infer_dtype' from 'tensorrt_llm.models.convert_utils' (/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/convert_utils.py)
> ```
> 
> If I do in the folder I added this to the first line in requirements.txt `--extra-index-url https://pypi.nvidia.com/ tensorrt-llm` and afterwards `pip install -r requirements.txt`, the error is gone. I also had to uninstall and reinstall tensorrt for some reason. `pip list` gives the following before and after:
> 
> Before
> 
> ```
> tensorrt           10.4.0
> tensorrt-llm       0.14.0
> tokenizers         0.20.1
> tomli              2.0.2
> torch              2.4.0a0+3bcc3cddb5.nv24.7
> torchprofile       0.0.4
> torchvision        0.19.0a0
> tqdm               4.66.6
> transformers       4.45.1
> ```
> 
> After
> 
> ```
> tensorrt                 10.6.0.post1
> tensorrt-cu12            10.6.0.post1
> tensorrt-cu12-bindings   10.6.0.post1
> tensorrt-cu12-libs       10.6.0.post1
> tensorrt_llm             0.16.0.dev2024111900
> tokenizers               0.20.1
> tomli                    2.0.2
> torch                    2.5.1
> torchprofile             0.0.4
> torchvision              0.20.1
> tqdm                     4.66.6
> transformers             4.45.1
> triton                   3.1.0
> ```
> 
> The code for the Llamas repo I am using this, which could be the difference here also: https://huggingface.co/tartuNLP/Llammas-base-AEG

Thank you so much for your response.

With these changes, could you also execute launch_triton_server.py code?

Additionally, could you mention which tensorrtllm-backend branch did you clone?

**Comment by nv-guomingz** [comment]
> > I fixed this by doing `pip install -r requirements.txt` in `/opt/tritonserver/TensorRT_LLM/TensorRT-LLM/examples/llama`. I had to add an --extra-index-url for tensorrt_llm though. I didn't get the `infer_dtype` error afterwards.
> 
> Thank you for your response :)
> 
> Could you please tell me your TensorRT-LLM, tensorrtllm-backend as well as Docker container image versions?
> 
> Also, it would be very helpful if you could list down installed libraries here using "pip list" within your docker container.
> 
> I am still facing the infer_dtype issue with 0.14.0 TensorRT-LLM version even after using--extra-index-url and if I use the latest version (0.16.0) there is tensorrt version compatibility issue
> 
> ```
> 0.14.0
> 201it [00:07, 25.98it/s]
> Traceback (most recent call last):
>   File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 518, in <module>
>     main()
>   File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 510, in main
>     convert_and_save_hf(args)
>   File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 452, in convert_and_save_hf
>     execute(args.workers, [convert_and_save_rank] * world_size, args)
>   File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 459, in execute
>     f(args, rank)
>   File "/opt/tritonserver/TensorRT_LLM_KARI/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 438, in convert_and_save_rank
>     llama = LLaMAForCausalLM.from_hugging_face(
>   File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 360, in from_hugging_face
>     loader.generate_tllm_weights(model)
>   File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/model_weights_loader.py", line 408, in generate_tllm_weights
>     self.load(tllm_key,
>   File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/model_weights_loader.py", line 296, in load
>     v = sub_module.postprocess(tllm_key, v, **postprocess_kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/layers/linear.py", line 407, in postprocess
>     weights = weights.to(str_dtype_to_torch(self.dtype))
> AttributeError: 'NoneType' object has no attribute 'to'
> ```

you need to add --use_share_embedding flag for converting llama 3. checkpoint.

**Comment by DeekshithaDPrakash** [comment]
After numerous trials and errors, and thanks to the amazing support from the community, I successfully resolved the Triton serving issue for LLaMA 3.2. 

Here's a detailed step-by-step guide to help others facing the same problem!

1. Make docker image: choose 24.10 as it comes with transformers 4.45.1

```python
docker run -it --net host --shm-size=4g --name your_docker_image_name --ulimit memlock=-1 --ulimit stack=67108864 --gpus '"device=0"' -v /your_local_repo_with_llama3.2_model_or_finetuned_llama3.2:/opt/tritonserver/TensorRT_LLM nvcr.io/nvidia/tritonserver:24.10-trtllm-python-py3
```
2. Clone the tesnorrtllm_backend : I chose the same release branch as my docker container version

`cd TensorRT_LLM`   ----> this is the directory/folder we mounted when creating docker image
```python
git clone -b r24.10 https://github.com/triton-inference-server/tensorrtllm_backend.git
```

`cd tensorrtllm_backend`

```python
 #adding tensorrt_llm submodule
git lfs install
git submodule update --init --recursive
```

3. Define checkpoint file path and others

```python
CONVERT_CHKPT_SCRIPT=/opt/tritonserver/TensorRT_LLM/tensorrtllm_backend/tensorrt_llm/examples/llama/convert_checkpoint.py
LLAMA_MODEL=/opt/tritonserver/TensorRT_LLM/llama3.2_model
UNIFIED_CKPT_PATH=/opt/tritonserver/TensorRT_LLM/ckpt/llaam32/3b
ENGINE_DIR=/opt/tritonserver/TensorRT_LLM/engines/1-gpu

```
4. Execute convert_checkpoint.py with --use_embedding_sharing tag

```python
python3 ${CONVERT_CHKPT_SCRIPT} --model_dir ${LLAMA_MODEL} --output_dir ${UNIFIED_CKPT_PATH} --dtype float16 --use_embedding_sharing
``` 

5. Build the engine
```python
trtllm-build --checkpoint_dir ${UNIFIED_CKPT_PATH} \
            --remove_input_padding enable \
            --gpt_attention_plugin float16 \
            --context_fmha enable \
            --gemm_plugin float16 \
            --output_dir ${ENGINE_DIR} \
            --paged_kv_cache enable \
            --max_batch_size 8
``` 

6. Make config.pbtxt files using inflight_batcher_llm

```python
COMMON_DIR=/opt/tritonserver/
cp -r /opt/tritonserver/TensorRT_LLM_KARI/tensorrtllm_backend/tools ${COMMON_DIR}
cp -r /opt/tritonserver/TensorRT_LLM_KARI/tensorrtllm_backend/scripts ${COMMON_DIR}
cp -R /opt/tritonserver/TensorRT_LLM_KARI/tensorrtllm_backend/all_models/inflight_batcher_llm /opt/tritonserver/.

```
```python
python3 ${COMMON_DIR}tools/fill_template.py -i ${COMMON_DIR}inflight_batcher_llm/preprocessing/config.pbtxt tokenizer_dir:${LLAMA_MODEL},tokenizer_type:auto,triton_max_batch_size:64,preprocessing_instance_count:1

python3 ${COMMON_DIR}tools/fill_template.py -i ${COMMON_DIR}inflight_batcher_llm/postprocessing/config.pbtxt tokenizer_dir:${LLAMA_MODEL},tokenizer_type:auto,triton_max_batch_size:64,postprocessing_instance_count:1

python3 ${COMMON_DIR}tools/fill_template.py -i ${COMMON_DIR}inflight_batcher_llm/tensorrt_llm_bls/config.pbtxt triton_max_batch_size:64,decoupled_mode:True,bls_instance_count:1,accumulate_tokens:False

python3 ${COMMON_DIR}tools/fill_template.py -i ${COMMON_DIR}inflight_batcher_llm/ensemble/config.pbtxt triton_max_batch_size:64

python3 ${COMMON_DIR}tools/fill_template.py -i ${COMMON_DIR}inflight_batcher_llm/tensorrt_llm/config.pbtxt triton_backend:tensorrtllm,triton_max_batch_size:64,decoupled_mode:True,max_beam_width:1,engine_dir:${ENGINE_DIR},max_tokens_in_paged_kv_cache:81920,max_attention_window_size:81920,kv_cache_free_gpu_mem_fraction:0.5,exclude_input_in_output:True,enable_kv_cache_reuse:False,batching_strategy:inflight_fused_batching,max_queue_delay_microseconds:0
```

7. Launch the triton server with desired port numbers
```python
python3 /opt/tritonserver/scripts/launch_triton_server.py --world_size 1 --model_repo=/opt/tritonserver/inflight_batcher_llm --http_port 8010 --grpc_port 8011 --metrics_port 8012
````

**Comment by byshiue** [comment]
Thank you for the update. Close this bug since the issue is resolved.
