### ISSUE TITLE
Using a Turing architecture GPU to quantize the model resulted in incorrect output.

### ISSUE THREAD

**Issue by Minami-su** [NVIDIA/TensorRT-LLM#278]
I used a 2080 Ti Turing architecture GPU to quantize the llama and baichuan model, which resulted in incorrect output. However, when I quantized the model using a 3090 Ampere architecture GPU, the results were correct. Is it possible to support Turing architecture GPUs?

**Comment by byshiue** [comment]
Have you compiled TensorRT LLM with SM 75?

**Comment by Minami-su** [comment]
I don't know what that means. Could you please explain it in detail? I installed the official docker method installation, and then compiled llm on 2080ti, and 2080ti is indeed sm75,

**Comment by Minami-su** [comment]
I inquired about this in another TensorRT LLM project, and the author there responded that the official TensorRT LLM does not support the Turing architecture.
https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM/issues/18#issuecomment-1793268067

**Comment by haojiwei** [comment]
The default setting does not contain SM 75. Can you try to set cuda_architectures=75-real in script/build_wheel.py？ @Minami-su

**Comment by Minami-su** [comment]
> The default setting does not contain SM 75. Can you try to set cuda_architectures=75-real in script/build_wheel.py？ @Minami-su

thank you I will try it.

**Comment by Minami-su** [comment]
I executed the following command: "make -C docker release_build CUDA_ARCHS="75-real." The problem has been resolved, and the compiled quantized LLM now produces the correct results. Thank you! @haojiwei
