### ISSUE TITLE
Open MPI error while converting model checkpoints

### ISSUE THREAD

**Issue by adityarajsahu** [NVIDIA/TensorRT-LLM#2801]
I am trying to convert Qwen/Qwen2.5-0.5B-Instruct model to TensorRT-LLM engine and perform inference within a docker container.
Here is my Dockerfile
```
# Base Image
FROM nvcr.io/nvidia/tensorrt:23.11-py3

# Install necessary dependencies for TensorRT conversion
RUN apt-get update && apt-get -y install openmpi-bin libopenmpi-dev git

# Clone TensorRT-LLM and install dependencies
RUN git clone https://github.com/NVIDIA/TensorRT-LLM/

RUN pip install -r TensorRT-LLM/examples/qwen/requirements.txt
RUN pip install tensorrt_llm==0.17.0.dev2024121700 --extra-index-url https://pypi.nvidia.com

# Set working directory
WORKDIR /workspace

# Copy local project files into the container
COPY . .

# Default shell
CMD ["/bin/bash"]
```

I am running the docker container using the command
```docker run --rm --gpus=all -it qwen_trtllm```

When I am trying to convert the huggingface model to TensorRT LLM checkpoints, using the command
```python3 convert_checkpoint.py --model_dir Qwen2.5-0.5B-Instruct --output_dir qwen_ckpt --dtype float16```

then, I am getting the following error
```
--------------------------------------------------------------------------
It looks like opal_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during opal_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_shmem_base_select failed
  --> Returned value -1 instead of OPAL_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_init failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Error" (-1) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[d4d9dc5ec29a:00654] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

How to resolve this error?

**Comment by dominicshanshan** [comment]
@adityarajsahu from the error msg seems your env build is missing some packages, please refer to [here](https://nvidia.github.io/TensorRT-LLM/installation/build-from-source-linux.html) to build docker and build TRT-LLM inside docker. 
1. `make -C docker release_build CUDA_ARCHS="90-real"` (CUDA_ARCHS depends on your GPU arch, Hopper is sm90, Ampere is sm80, Blackwell is sm100)
2. After docker image is build, use `docker run` then `git clone https://github.com/NVIDIA/TensorRT-LLM/`, run `python3 ./scripts/build_wheel.py --cuda_architectures "90-real" --trt_root /usr/local/tensorrt -ccache --benchmarks --micro_benchamrks`

I just tested Qwen2.5-0.5B-Instruct it is fine

**Comment by adityarajsahu** [comment]
Thanks, I have resolved the issue.
