### ISSUE TITLE
Nccl errors when running codellama 34b on 4 A100 gpus

### ISSUE THREAD

**Issue by johnjyang** [NVIDIA/TensorRT-LLM#504]
Similar to issue #213, I ran into nccl errors when running codellama 34b on 4 A100 gpus.

docker container was built through `make -C docker release_build`, ran through `make -C docker release_run IPC=host ULIMIT="memlock=-1 --ulimit stack=67108864" GPUS=all` (after trying the solution mentioned in issue #54)

In the container, a build of the same codellama 34b for 2 gpus runs successfully with the command: `mpirun -n 2 --allow-run-as-root python summarize.py --test_trt_llm --hf_model_location CodeLlama-34b-Instruct-hf/ --data_type fp16 --engine_dir ./tmp/codellama/34B-Instruct/trt_engines/fp16/2-gpu/`

but fails for the 4 gpus command, after building for 4 gpus:
```
mpirun -n 4 --allow-run-as-root python summarize.py --test_trt_llm --hf_model_location CodeLlama-34b-Instruct-hf/ --data_type fp16 --engine_dir ./tmp/codellama/34B-Instruct/trt_engines/fp16/4-gpu/
```

error:
```
Failed, NCCL error /src/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/allreducePlugin.cpp:295 'internal error - please report this issue to the NCCL developers'
Failed, NCCL error /src/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/allreducePlugin.cpp:295 'internal error - please report this issue to the NCCL developers'
Failed, NCCL error /src/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/allreducePlugin.cpp:295 'internal error - please report this issue to the NCCL developers'
Failed, NCCL error /src/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/allreducePlugin.cpp:295 'internal error - please report this issue to the NCCL developers'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[1799,1],3]
  Exit code:    1
--------------------------------------------------------------------------
```

An nccl test in the container fails for 4 gpus too with `./build/all_reduce_perf -b 8 -e 128M -f 2 -g 4` (passes for 1, 2, and 3 gpus)

nccl test error:

```
# nThread 1 nGpus 4 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 agg iters: 1 validation: 1 graph: 0
#
# Using devices
#  Rank  0 Group  0 Pid   1302 on e2e-97-151-release device  0 [0x01] NVIDIA A100 80GB PCIe
#  Rank  1 Group  0 Pid   1302 on e2e-97-151-release device  1 [0x01] NVIDIA A100 80GB PCIe
#  Rank  2 Group  0 Pid   1302 on e2e-97-151-release device  2 [0x01] NVIDIA A100 80GB PCIe
#  Rank  3 Group  0 Pid   1302 on e2e-97-151-release device  3 [0x01] NVIDIA A100 80GB PCIe
e2e-97-151-release: Test NCCL failure common.cu:954 'internal error - please report this issue to the NCCL developers / '
 .. e2e-97-151-release pid 1302: Test failure common.cu:844
```

The container nccl and cuda versions are:

```
ii  libnccl-dev                     2.18.3-1+cuda12.2                          amd64        NVIDIA Collective Communication Library (NCCL) Development Files
ii  libnccl2                        2.18.3-1+cuda12.2                          amd64        NVIDIA Collective Communication Library (NCCL) Runtime
```

Running the same nccl test for 4 gpus passes outside of the container. With the nccl and cuda versions:

```
ii  libnccl-dev                           2.19.4-1+cuda12.1                     amd64        NVIDIA Collective Communication Library (NCCL) Development Files
ii  libnccl2                              2.19.4-1+cuda12.1                     amd64        NVIDIA Collective Communication Library (NCCL) Runtime
```

Please let me know if there is any more information I should provide. Appreciate any help!

**Comment by wodeqiansuihan** [comment]
像是网卡没配置好

**Comment by byshiue** [comment]
If you cannot run the nccl successfully, that means there are some issues in your environment setting and we may not provide too many help. Of course, we are happy to provide help if we have any idea or clue.

**Comment by johnjyang** [comment]
Solved by setting NCCL_P2P_DISABLE=1. Thanks for the pointers!

**Comment by byshiue** [comment]
Thank you for update. Close this bug. Feel fee to reopen if needed.
