### ISSUE TITLE
Assertion failed: d == a + length (/app/tensorrt_llm/cpp/tensorrt_llm/plugins/gptAttentionCommon/gptAttentionCommon.cpp:320

### ISSUE THREAD

**Issue by zhaoxjmail** [NVIDIA/TensorRT-LLM#583]
[TensorRT-LLM][INFO] Loaded engine size: 15448 MiB
[TensorRT-LLM][ERROR] tensorrt_llm::common::TllmException: [TensorRT-LLM][ERROR] Assertion failed: d == a + length (/app/tensorrt_llm/cpp/tensorrt_llm/plugins/gptAttentionCommon/gptAttentionCommon.cpp:320)
1       0x7f6ce803be0b /opt/tritonserver/backends/tensorrtllm/libnvinfer_plugin_tensorrt_llm.so.9(+0x35e0b) [0x7f6ce803be0b]
2       0x7f6ce809746c tensorrt_llm::plugins::GPTAttentionPluginCommon::GPTAttentionPluginCommon(void const*, unsigned long) + 908
3       0x7f6ce80a9b2d tensorrt_llm::plugins::GPTAttentionPlugin::GPTAttentionPlugin(void const*, unsigned long) + 13
4       0x7f6ce80a9b72 tensorrt_llm::plugins::GPTAttentionPluginCreator::deserializePlugin(char const*, void const*, unsigned long) + 50
5       0x7f6d1ff13c36 /usr/local/tensorrt/lib/libnvinfer.so.9(+0x10a0c36) [0x7f6d1ff13c36]
6       0x7f6d1ff22a8e /usr/local/tensorrt/lib/libnvinfer.so.9(+0x10afa8e) [0x7f6d1ff22a8e]
7       0x7f6d1fead737 /usr/local/tensorrt/lib/libnvinfer.so.9(+0x103a737) [0x7f6d1fead737]
8       0x7f6d1feab81e /usr/local/tensorrt/lib/libnvinfer.so.9(+0x103881e) [0x7f6d1feab81e]
9       0x7f6d1fec252b /usr/local/tensorrt/lib/libnvinfer.so.9(+0x104f52b) [0x7f6d1fec252b]
10      0x7f6d1fec4fa2 /usr/local/tensorrt/lib/libnvinfer.so.9(+0x1051fa2) [0x7f6d1fec4fa2]
11      0x7f6d1fec537c /usr/local/tensorrt/lib/libnvinfer.so.9(+0x105237c) [0x7f6d1fec537c]
12      0x7f6d1fef7051 /usr/local/tensorrt/lib/libnvinfer.so.9(+0x1084051) [0x7f6d1fef7051]
13      0x7f6d1fef7e17 /usr/local/tensorrt/lib/libnvinfer.so.9(+0x1084e17) [0x7f6d1fef7e17]
14      0x7f6d2e8d5594 /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0xed594) [0x7f6d2e8d5594]
15      0x7f6d2e84ef4e /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x66f4e) [0x7f6d2e84ef4e]
16      0x7f6d2e83ec0c /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x56c0c) [0x7f6d2e83ec0c]
17      0x7f6d2e8395f5 /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x515f5) [0x7f6d2e8395f5]
18      0x7f6d2e8374db /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x4f4db) [0x7f6d2e8374db]
19      0x7f6d2e81b182 /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x33182) [0x7f6d2e81b182]
20      0x7f6d2e81b235 TRITONBACKEND_ModelInstanceInitialize + 101
21      0x7f6e2319aa86 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x1a4a86) [0x7f6e2319aa86]
22      0x7f6e2319bcc6 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x1a5cc6) [0x7f6e2319bcc6]
23      0x7f6e2317ec15 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x188c15) [0x7f6e2317ec15]
24      0x7f6e2317f256 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x189256) [0x7f6e2317f256]
25      0x7f6e2318b27d /opt/tritonserver/bin/../lib/libtritonserver.so(+0x19527d) [0x7f6e2318b27d]
26      0x7f6e227f9ee8 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x99ee8) [0x7f6e227f9ee8]
27      0x7f6e2317597b /opt/tritonserver/bin/../lib/libtritonserver.so(+0x17f97b) [0x7f6e2317597b]
28      0x7f6e23185695 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x18f695) [0x7f6e23185695]

**Comment by moseshu** [comment]
> [TensorRT-LLM][INFO] Loaded engine size: 15448 MiB [TensorRT-LLM][ERROR] tensorrt_llm::common::TllmException: [TensorRT-LLM][ERROR] Assertion failed: d == a + length (/app/tensorrt_llm/cpp/tensorrt_llm/plugins/gptAttentionCommon/gptAttentionCommon.cpp:320) 1 0x7f6ce803be0b /opt/tritonserver/backends/tensorrtllm/libnvinfer_plugin_tensorrt_llm.so.9(+0x35e0b) [0x7f6ce803be0b] 2 0x7f6ce809746c tensorrt_llm::plugins::GPTAttentionPluginCommon::GPTAttentionPluginCommon(void const*, unsigned long) + 908 3 0x7f6ce80a9b2d tensorrt_llm::plugins::GPTAttentionPlugin::GPTAttentionPlugin(void const*, unsigned long) + 13 4 0x7f6ce80a9b72 tensorrt_llm::plugins::GPTAttentionPluginCreator::deserializePlugin(char const*, void const*, unsigned long) + 50 5 0x7f6d1ff13c36 /usr/local/tensorrt/lib/libnvinfer.so.9(+0x10a0c36) [0x7f6d1ff13c36] 6 0x7f6d1ff22a8e /usr/local/tensorrt/lib/libnvinfer.so.9(+0x10afa8e) [0x7f6d1ff22a8e] 7 0x7f6d1fead737 /usr/local/tensorrt/lib/libnvinfer.so.9(+0x103a737) [0x7f6d1fead737] 8 0x7f6d1feab81e /usr/local/tensorrt/lib/libnvinfer.so.9(+0x103881e) [0x7f6d1feab81e] 9 0x7f6d1fec252b /usr/local/tensorrt/lib/libnvinfer.so.9(+0x104f52b) [0x7f6d1fec252b] 10 0x7f6d1fec4fa2 /usr/local/tensorrt/lib/libnvinfer.so.9(+0x1051fa2) [0x7f6d1fec4fa2] 11 0x7f6d1fec537c /usr/local/tensorrt/lib/libnvinfer.so.9(+0x105237c) [0x7f6d1fec537c] 12 0x7f6d1fef7051 /usr/local/tensorrt/lib/libnvinfer.so.9(+0x1084051) [0x7f6d1fef7051] 13 0x7f6d1fef7e17 /usr/local/tensorrt/lib/libnvinfer.so.9(+0x1084e17) [0x7f6d1fef7e17] 14 0x7f6d2e8d5594 /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0xed594) [0x7f6d2e8d5594] 15 0x7f6d2e84ef4e /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x66f4e) [0x7f6d2e84ef4e] 16 0x7f6d2e83ec0c /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x56c0c) [0x7f6d2e83ec0c] 17 0x7f6d2e8395f5 /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x515f5) [0x7f6d2e8395f5] 18 0x7f6d2e8374db /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x4f4db) [0x7f6d2e8374db] 19 0x7f6d2e81b182 /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x33182) [0x7f6d2e81b182] 20 0x7f6d2e81b235 TRITONBACKEND_ModelInstanceInitialize + 101 21 0x7f6e2319aa86 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x1a4a86) [0x7f6e2319aa86] 22 0x7f6e2319bcc6 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x1a5cc6) [0x7f6e2319bcc6] 23 0x7f6e2317ec15 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x188c15) [0x7f6e2317ec15] 24 0x7f6e2317f256 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x189256) [0x7f6e2317f256] 25 0x7f6e2318b27d /opt/tritonserver/bin/../lib/libtritonserver.so(+0x19527d) [0x7f6e2318b27d] 26 0x7f6e227f9ee8 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x99ee8) [0x7f6e227f9ee8] 27 0x7f6e2317597b /opt/tritonserver/bin/../lib/libtritonserver.so(+0x17f97b) [0x7f6e2317597b] 28 0x7f6e23185695 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x18f695) [0x7f6e23185695]

change your version to v0.6.1 ,don't use main branch.

**Comment by byshiue** [comment]
It is often because you build the engine on one commit, and run on another commit, and the parameters of the plugin are different. 

Please try rebuilding the engine.

**Comment by byshiue** [comment]
Close this bug because another same issue is resolved. Feel free to ask here if you still have question/issue. We will reopen this issue.

**Comment by wangqy1216** [comment]
> It is often because you build the engine on one commit, and run on another commit, and the parameters of the plugin are different.
> 
> Please try rebuilding the engine.

How do I know which commit I am running on?

**Comment by byshiue** [comment]
> > It is often because you build the engine on one commit, and run on another commit, and the parameters of the plugin are different.
> > Please try rebuilding the engine.
> 
> How do I know which commit I am running on?

In the older version of TensorRT, we don't have way to check that. In newer TensorRT-LLM, you could see the TRT LLM version when you run TRT-LLM.
