### ISSUE TITLE
Unable to use smoothquant on llama-70b using 4xA100

### ISSUE THREAD

**Issue by AbhinavDutta** [NVIDIA/TensorRT-LLM#622]
I am trying to quantize llama 70b on 4xA100 (82 GB each) and am running out of memory. Surely, this can be avoided, right? 320 GB should be enough! Maybe there are some config params I can pass to deal with this ? (I was able to quantize llama 7b on the same machine, and observed 7GB and 11 GB usage during the calibration and saving weights phase respectively. While quantizing llama 70b, I see 70 GB usage, so it roughly scales and the calibration phase ends successfully but the second phase leads too OOM, I am guessing the second stage wants 110 GB! )
This is the error I get when I run hf_llama_convert.py

`
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/hf_llama_convert.py", line 335, in <module>
    hf_gpt_converter(args)
  File "/code/tensorrt_llm/examples/llama/hf_llama_convert.py", line 188, in hf_gpt_converter
    smooth_llama_model(model, act_range, args.smoothquant,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/code/tensorrt_llm/examples/llama/hf_llama_convert.py", line 103, in smooth_llama_model
    smoother = smooth_gemm_fc1_gate(module.mlp.gate_proj.weight,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/code/tensorrt_llm/examples/llama/smoothquant.py", line 108, in smooth_gemm_fc1_gate
    [gemm.abs().max(dim=0, keepdim=True)[0] for gemm in gemm_weights],
  File "/code/tensorrt_llm/examples/llama/smoothquant.py", line 108, in <listcomp>
    [gemm.abs().max(dim=0, keepdim=True)[0] for gemm in gemm_weights],
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 896.00 MiB. GPU 1 has a total capacty of 79.15 GiB of which 215.25 MiB is free. Process 2708090 has 78.93 GiB memory in use. Of the allocated memory 75.87 GiB is allocated by PyTorch, and 2.57 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`

**Comment by Tracin** [comment]
Hi, which branch did you use? Please try on `0.6.1`

**Comment by AbhinavDutta** [comment]
hey, I was using 0.5.0, switching to the mentioned version indeed solved my problem. thanks!
