### ISSUE TITLE
CUDA error occured when input length and output length are too long

### ISSUE THREAD

**Issue by littletomatodonkey** [NVIDIA/TensorRT-LLM#675]
Hi, when i set export the model with input length as 8192 and output length as 4096, and infer using  `max_output_len=10240`, the following error occured.(Just 72G is used and no OOM)

```
  File "/usr/local/lib/python3.9/dist-packages/tensorrt_llm/runtime/generation.py", line 514, in wrapper
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/tensorrt_llm/runtime/generation.py", line 1887, in decode
    return self.decode_regular(
  File "/usr/local/lib/python3.9/dist-packages/tensorrt_llm/runtime/generation.py", line 1659, in decode_regular
    should_stop, next_step_buffer, tasks, context_lengths, host_context_lengths, attention_mask, logits = self.handle_per_step(
  File "/usr/local/lib/python3.9/dist-packages/tensorrt_llm/runtime/generation.py", line 1507, in handle_per_step
    model_inputs = self._prepare_generation_inputs(
  File "/usr/local/lib/python3.9/dist-packages/tensorrt_llm/runtime/generation.py", line 1294, in _prepare_generation_inputs
    last_token_ids = torch.ones_like(context_lengths)
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions
```

However, when i infer using max_output_len=6144, everything is normal. Other information.

* model: Yi-34B with float16
* device: A100
* version: trt-llm release/0.5.0

Could you please help to see what's the problem? Thanks.

**Comment by byshiue** [comment]
Please try the 0.6.1 or latest main branch.

**Comment by littletomatodonkey** [comment]
release0.6.1 works for me, thanks!
