### ISSUE TITLE
TensorRT-LLM crashed using in Windows WSL2 docker

### ISSUE THREAD

**Issue by songkq** [NVIDIA/TensorRT-LLM#886]
@Superjomn Hi, could you please give some advice for this issue? It crashed and raised Out of Memory Error. However, there are enough empty VRAM (only 19032MiB/24576MiB used).

<img width="913" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/30183023/75f0e0da-2953-469b-a037-94a71e347b91">

```
Env: 
win10 wsl2 
docker 24.0.7 
CUDA Version: 12.3 
GPU RTX 3090 
Driver Version: 546.33
Model: Deepseek-7B

### build a docker image w/ main branch
git clone https://github.com/triton-inference-server/tensorrtllm_backend.git
cd tensorrtllm_backend
git lfs install
git submodule update --init --recursive

# Use the Dockerfile to build the backend in a container
# For x86_64
DOCKER_BUILDKIT=1 docker build -t triton_trt_llm -f dockerfile/Dockerfile.trt_llm_backend .


### convert hf model to ft w/ int8_kv_cache calibration:

python -u hf_deepseek_convert.py -i deepseek/ -o ./deepseek/engine/int8_kv_cache --calibrate-kv-cache -t fp16

### convert ft model to engine:

python -u build.py --ft_model_dir ./deepseek/engine/int8_kv_cache/1-gpu/ --vocab_size 102400 \
                --dtype float16 \
                --max_batch_size 4 \
                --n_positions 4096 \
                --max_input_len 3584 \
                --max_output_len 512 \
                --use_inflight_batching \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --paged_kv_cache \
                --int8_kv_cache \
                --use_weight_only \
                --weight_only_precision int8 \
                --output_dir ./deepseek/engine/int8/1-gpu/


### tensorrt-llm config.pbtxt



name: "tensorrt_llm"
backend: "tensorrtllm"
max_batch_size: 4

model_transaction_policy {
  decoupled: true
}

dynamic_batching {
    preferred_batch_size: [ 4 ]
    max_queue_delay_microseconds: 50000
}

input [
  {
    name: "input_ids"
    data_type: TYPE_INT32
    dims: [ -1 ]
    allow_ragged_batch: true
  },
  {
    name: "input_lengths"
    data_type: TYPE_INT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
  },
  {
    name: "request_output_len"
    data_type: TYPE_INT32
    dims: [ 1 ]
  },
  {
    name: "draft_input_ids"
    data_type: TYPE_INT32
    dims: [ -1 ]
    optional: true
    allow_ragged_batch: true
  },
  {
    name: "end_id"
    data_type: TYPE_INT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "pad_id"
    data_type: TYPE_INT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "stop_words_list"
    data_type: TYPE_INT32
    dims: [ 2, -1 ]
    optional: true
    allow_ragged_batch: true
  },
  {
    name: "bad_words_list"
    data_type: TYPE_INT32
    dims: [ 2, -1 ]
    optional: true
    allow_ragged_batch: true
  },
  {
    name: "embedding_bias"
    data_type: TYPE_FP32
    dims: [ -1 ]
    optional: true
    allow_ragged_batch: true
  },
  {
    name: "beam_width"
    data_type: TYPE_INT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "temperature"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "runtime_top_k"
    data_type: TYPE_INT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "runtime_top_p"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "len_penalty"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "repetition_penalty"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "min_length"
    data_type: TYPE_INT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "presence_penalty"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "random_seed"
    data_type: TYPE_UINT64
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "return_log_probs"
    data_type: TYPE_BOOL
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "stop"
    data_type: TYPE_BOOL
    dims: [ 1 ]
    optional: true
  },
  {
    name: "streaming"
    data_type: TYPE_BOOL
    dims: [ 1 ]
    optional: false
  },
  {
    name: "prompt_embedding_table"
    data_type: TYPE_FP16
    dims: [ -1, -1 ]
    optional: true
    allow_ragged_batch: true
  },
  {
    name: "prompt_vocab_size"
    data_type: TYPE_INT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  }
]
output [
  {
    name: "output_ids"
    data_type: TYPE_INT32
    dims: [ -1, -1 ]
  },
  {
    name: "sequence_length"
    data_type: TYPE_INT32
    dims: [ -1 ]
  },
  {
    name: "cum_log_probs"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "output_log_probs"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]
  }
]
instance_group [
  {
    count: 1
    kind : KIND_CPU
  }
]
parameters: {
  key: "max_beam_width"
  value: {
    string_value: "1"
  }
}
parameters: {
  key: "FORCE_CPU_ONLY_INPUT_TENSORS"
  value: {
    string_value: "no"
  }
}
parameters: {
  key: "gpt_model_type"
  value: {
    string_value: "inflight_fused_batching"
  }
}
parameters: {
  key: "gpt_model_path"
  value: {
    string_value: "/workspace/model_repos/Ensemble/tensorrt_llm/1/"
  }
}
parameters: {
  key: "max_tokens_in_paged_kv_cache"
  value: {
    string_value: "unspecified"
  }
}
parameters: {
  key: "max_attention_window_size"
  value: {
    string_value: "max_sequence_length"
  }
}
parameters: {
  key: "batch_scheduler_policy"
  value: {
    string_value: "max_utilization"
  }
}
parameters: {
  key: "kv_cache_free_gpu_mem_fraction"
  value: {
    string_value: "0.5"
  }
}
parameters: {
  key: "max_num_sequences"
  value: {
    string_value: "8"
  }
}
parameters: {
  key: "enable_trt_overlap"
  value: {
    string_value: "true"
  }
}
parameters: {
  key: "exclude_input_in_output"
  value: {
    string_value: "true"
  }
}
parameters: {
  key: "enable_kv_cache_reuse"
  value: {
    string_value: "false"
  }
}
parameters: {
  key: "normalize_log_probs"
  value: {
    string_value: "true"
  }
}


```

```
[TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 8
[TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 4
[TensorRT-LLM][INFO] TRTGptModel mMaxAttentionWindowSize: 4096
[TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 1
[TensorRT-LLM][INFO] TRTGptModel normalizeLogProbs: 1
[TensorRT-LLM][INFO] Loaded engine size: 7396 MiB
[TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 8038, GPU 9935 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 8038, GPU 9943 (MiB)
[TensorRT-LLM][WARNING] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.4
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +7393,
 now: CPU 0, GPU 7393 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 8073, GPU 10325 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 8073, GPU 10333 (MiB)
[TensorRT-LLM][WARNING] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.4
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0
, now: CPU 0, GPU 7393 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +10, now: CPU 8093, GPU 10351 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +0, GPU +12, now: CPU 8093, GPU 10363 (MiB)
[TensorRT-LLM][WARNING] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.4
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0
, now: CPU 0, GPU 7393 (MiB)
[TensorRT-LLM][INFO] Allocate 7486832640 bytes for k/v cache.
[TensorRT-LLM][INFO] Using 30464 total tokens in paged KV cache, and 32 blocks per sequence
I0115 14:43:29.114863 96 backend_model_instance.cc:772] Starting backend thread for tensorrt_llm_0_0 at nice 0
on device 0...
I0115 14:43:29.115357 96 dynamic_batch_scheduler.cc:297] Starting dynamic-batcher thread for tensorrt_llm at ni
ce 0...
I0115 14:43:29.115364 96 model_lifecycle.cc:818] successfully loaded 'tensorrt_llm'
I0115 14:43:29.121607 96 model_lifecycle.cc:461] loading: ensemble:1
I0115 14:43:29.121916 96 ensemble_model.cc:55] ensemble model for ensemble

I0115 14:43:29.122092 96 model_lifecycle.cc:818] successfully loaded 'ensemble'

....


[TensorRT-LLM][ERROR] [TensorRT-LLM][ERROR] CUDA runtime error in ::cudaHostAlloc(ptr, n, cudaHostAllocDefault)
: out of memory (/app/tensorrt_llm/cpp/tensorrt_llm/runtime/tllmBuffers.h:143)
1       0x7fcafb6e2c05 /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x3fc05) [0x7fcafb6e2c0
5]
2       0x7fcafb76fe4d /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0xcce4d) [0x7fcafb76fe4
d]
3       0x7fcafb768a6a /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0xc5a6a) [0x7fcafb768a6
a]
4       0x7fcafb720373 /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x7d373) [0x7fcafb72037
3]
5       0x7fcafb6e4139 /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x41139) [0x7fcafb6e413
9]
6       0x7fcafb6e504c /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x4204c) [0x7fcafb6e504
c]
7       0x7fcafb6e5331 /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x42331) [0x7fcafb6e533
1]
8       0x7fcafb6e6797 /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x43797) [0x7fcafb6e679
7]
9       0x7fcafb6eac5b /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x47c5b) [0x7fcafb6eac5
b]
10      0x7fcafb6dfb95 TRITONBACKEND_ModelInstanceExecute + 101
11      0x7fcbc3b94774 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x19e774) [0x7fcbc3b94774]
12      0x7fcbc3b94adb /opt/tritonserver/bin/../lib/libtritonserver.so(+0x19eadb) [0x7fcbc3b94adb]
13      0x7fcbc3c9cecd /opt/tritonserver/bin/../lib/libtritonserver.so(+0x2a6ecd) [0x7fcbc3c9cecd]
14      0x7fcbc3b98f04 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x1a2f04) [0x7fcbc3b98f04]
15      0x7fcbc3464253 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xdc253) [0x7fcbc3464253]
16      0x7fcbc31f3ac3 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7fcbc31f3ac3]
17      0x7fcbc3285850 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x126850) [0x7fcbc3285850]
I0115 14:44:43.867013 96 stream_infer_handler.cc:554] ModelStreamInferHandler::StreamInferComplete, context 0,
0 step ISSUED, callback index 1, flags 1
I0115 14:44:43.867281 96 stream_infer_handler.cc:640] Failed for ID: <id_unknown>

I0115 14:44:43.867787 96 stream_infer_handler.cc:155] Process for ModelStreamInferHandler, rpc_ok=1, context 0,
 0 step WRITEREADY
I0115 14:44:43.868123 96 stream_infer_handler.cc:155] Process for ModelStreamInferHandler, rpc_ok=1, context 0,
 0 step WRITTEN
I0115 14:44:43.868338 96 infer_handler.h:1283] Received notification for ModelStreamInferHandler, 0
I0115 14:44:43.868560 96 stream_infer_handler.cc:155] Process for ModelStreamInferHandler, rpc_ok=1, context 0,
 0 step COMPLETE
I0115 14:44:43.868777 96 stream_infer_handler.cc:155] Process for ModelStreamInferHandler, rpc_ok=1, context 0,
 0 step FINISH
I0115 14:44:43.869006 96 infer_handler.h:1289] Done for ModelStreamInferHandler, 0
```

**Comment by byshiue** [comment]
It looks the program is really OOM during runtime. Could you try shorter input length and smaller batch size first?

**Comment by songkq** [comment]
@byshiue I'll try it. But everything is OK with the same configuration under Linux environment.

**Comment by songkq** [comment]
@byshiue Solved by upgrading to Win11.
Maybe a bug in Win10. After upgrading to Win11 (Enterprise 23H2 22631.3007), everything is OK.
