### ISSUE TITLE
gmake: Makefile: No such file or directory

### ISSUE THREAD

**Issue by Kelsey2018** [NVIDIA/TensorRT-LLM#92]
When I run "python3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt", I meet error

gmake: Makefile: No such file or directory
gmake: *** No rule to make target 'Makefile'.  Stop.

**Comment by byshiue** [comment]
Your problem may be same to this issue https://github.com/NVIDIA/TensorRT-LLM/issues/22, can you try the suggestions of the issue first?

**Comment by Kelsey2018** [comment]
Thank you! I solved this question with your help, but I meet another error ”RuntimeError: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.“

My CUDA is 12.2 and my NVIDIA driver is 520.56.06, so update the CUDA driver version is the only solution?

**Comment by byshiue** [comment]
> Thank you! I solved this question with your help, but I meet another error ”RuntimeError: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.“
> 
> My CUDA is 12.2 and my NVIDIA driver is 520.56.06, so update the CUDA driver version is the only solution?

There is a related issue you encounter https://github.com/NVIDIA/TensorRT-LLM/issues/83, it may be helpful.

**Comment by jdemouth-nvidia** [comment]
Closing - reopen if needed

**Comment by Taiinguyenn139** [comment]
When I run "python3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt", I meet error
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/51513839/1466c745-a2df-46e6-a766-ee368c804f93)

**Comment by Taiinguyenn139** [comment]
Hi there,

I found the solution about this. Just install git-lfs follow by this [link](https://stackoverflow.com/questions/48734119/git-lfs-is-not-a-git-command-unclear)
